---
# Source: kubedb/charts/kubedb-provisioner/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-kubedb-provisioner
  labels:
    helm.sh/chart: kubedb-provisioner-v0.51.0
    app.kubernetes.io/name: kubedb-provisioner
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.51.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedb-kubedb-provisioner
subjects:
- kind: ServiceAccount
  name: kubedb-kubedb-provisioner
  namespace: kubedb
