---
# Source: kubedb/charts/kubedb-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedb-kubedb-provisioner
  namespace: kubedb
  labels:
    helm.sh/chart: kubedb-provisioner-v0.51.0
    app.kubernetes.io/name: kubedb-provisioner
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.51.0"
    app.kubernetes.io/managed-by: Helm
