---
# Source: kubedb/charts/kubedb-ops-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubedb-kubedb-ops-manager
  namespace: kubedb
  labels:
    helm.sh/chart: kubedb-ops-manager-v0.38.0
    app.kubernetes.io/name: kubedb-ops-manager
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.38.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app.kubernetes.io/name: kubedb-ops-manager
    app.kubernetes.io/instance: kubedb
