apiVersion: catalog.kubedb.com/v1alpha1
kind: EtcdVersion
metadata:
  name: 3.6.4
spec:
  db:
    image: ghcr.io/appscode-images/etcd:v3.6.4
  exporter:
    image: ghcr.io/appscode-images/etcd:v3.6.4
  securityContext:
    runAsUser: 1000
  updateConstraints:
    allowlist:
    - '>= 3.6.4, <= 3.7.0'
  version: 3.6.4
