---
# Source: kubedb/charts/kubedb-kubestash-catalog/templates/kubedbverifier/kubedbverifier.yaml
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'kubedbverifier'
  labels:
    helm.sh/chart: kubedb-kubestash-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  args:
  - verify
  - --namespace=${namespace:=default}
  - --backupverificationsession=${backupVerificationSession:=}
  image: 'ghcr.io/kubedb/kubedb-verifier:v0.1.0'
