---
# Source: kubedb/charts/kubedb-autoscaler/templates/license-reader-cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-kubedb-autoscaler-license-reader
  labels:
    helm.sh/chart: kubedb-autoscaler-v0.36.0
    app.kubernetes.io/name: kubedb-autoscaler
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appscode:license-reader
subjects:
- kind: ServiceAccount
  name: kubedb-kubedb-autoscaler
  namespace: kubedb
