---
# Source: kubedb/charts/kubedb-autoscaler/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubedb-kubedb-autoscaler
  namespace: kubedb
  labels:
    helm.sh/chart: kubedb-autoscaler-v0.36.0
    app.kubernetes.io/name: kubedb-autoscaler
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app.kubernetes.io/name: kubedb-autoscaler
    app.kubernetes.io/instance: kubedb
