{{ if .Values.catalog.kafka }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaConnectorVersion
metadata:
  name: 'gcs-0.13'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  type: GCS
  connectorPlugin:
    image: '{{ include "image.ghcr" (merge (dict "_repo" "appscode-images/kafka-connector-gcs") $) }}:0.13.0'
  podSecurityPolicies:
    databasePolicyName: kafka-db
  securityContext:
    runAsUser: 1001
  version: '0.13'
{{ end }}
