apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedb-courier.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubedb-courier.labels" . | nindent 4 }}
spec:
  ports:
    # Port used to expose admission webhook apiserver
    - name: api
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    {{- include "kubedb-courier.selectorLabels" . | nindent 4 }}
