apiVersion: catalog.kubedb.com/v1alpha1
kind: HanaDBVersion
metadata:
  name: 2.0.76
spec:
  coordinator:
    image: ghcr.io/kubedb/hanadb-coordinator:v0.3.0
  db:
    image: saplabs/hanaexpress:2.00.076.00.20240701.1
  securityContext:
    runAsGroup: 79
    runAsUser: 12000
  updateConstraints:
    allowlist:
    - '>=2.0.76, <= 2.0.88'
  version: 2.0.76
