---
# Source: kubedb/charts/kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.15.0-s3.yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaConnectorVersion
metadata:
  name: 's3-2.15.0'
  labels:
    helm.sh/chart: kubedb-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  connectorPlugin:
    image: 'ghcr.io/appscode-images/kafka-connector-s3:2.15.0'
  securityContext:
    runAsUser: 1001
  type: S3
  version: 2.15.0
