---
# Source: kubedb/charts/kubedb-catalog/templates/kafkaconnector/kafkaconnector-1.14.1-mongodb.yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaConnectorVersion
metadata:
  name: 'mongodb-1.14.1'
  labels:
    helm.sh/chart: kubedb-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  connectorPlugin:
    image: 'ghcr.io/appscode-images/kafka-connector-mongodb:1.14.1'
  securityContext:
    runAsUser: 1001
  type: MongoDB
  version: 1.14.1
