---
# Source: kubedb/charts/kubedb-catalog/templates/kafkaconnector/kafkaconnector-3.0.5-jdbc.yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaConnectorVersion
metadata:
  name: 'jdbc-3.0.5.final'
  labels:
    helm.sh/chart: kubedb-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  connectorPlugin:
    image: 'ghcr.io/appscode-images/kafka-connector-jdbc:3.0.5.final'
  securityContext:
    runAsUser: 1001
  type: JDBC
  version: 3.0.5
