---
# Source: kubedb/charts/kubedb-catalog/templates/kafkaconnector/kafkaconnector-0.13.0-gcs.yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaConnectorVersion
metadata:
  name: 'gcs-0.13.0'
  labels:
    helm.sh/chart: kubedb-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  connectorPlugin:
    image: 'ghcr.io/appscode-images/kafka-connector-gcs:0.13.0'
  securityContext:
    runAsUser: 1001
  type: GCS
  version: 0.13.0
