---
# Source: kubedb/charts/kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.7.4-postgres.yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaConnectorVersion
metadata:
  name: 'postgres-2.7.4.final'
  labels:
    helm.sh/chart: kubedb-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  connectorPlugin:
    image: 'ghcr.io/appscode-images/kafka-connector-postgres:2.7.4.final'
  securityContext:
    runAsUser: 1001
  type: Postgres
  version: 2.7.4
