apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 9.6.0
spec:
  archiver:
    addon:
      name: mysql-addon
      tasks:
        fullBackup:
          name: physical-backup
        fullBackupRestore:
          name: physical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
        volumeSnapshot:
          name: volume-snapshot
    walg:
      image: ghcr.io/kubedb/mysql-archiver:(v0.27.0)_9.1.0
  coordinator:
    image: ghcr.io/kubedb/mysql-coordinator:v0.44.0
  courier:
    cli:
      image: ghcr.io/kubedb/kubedb-migrator-mysql:v0.6.0
    statusReporter:
      image: ghcr.io/kubedb/kubedb-courier:v0.6.0
  db:
    image: ghcr.io/appscode-images/mysql:9.6.0-oracle
  distribution: Official
  exporter:
    image: ghcr.io/kubedb/mysqld-exporter:v0.18.0
  gitSyncer:
    image: registry.k8s.io/git-sync/git-sync:v4.4.2
  initContainer:
    image: ghcr.io/kubedb/mysql-init:0.1.0
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: ghcr.io/kubedb/replication-mode-detector:v0.53.0
  router:
    image: ghcr.io/appscode-images/mysql-router:9.6.0
  routerInitContainer:
    image: ghcr.io/kubedb/mysql-router-init:v0.44.0
  securityContext:
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: mysql-backup-8.0.21
      restoreTask:
        name: mysql-restore-8.0.21
  ui:
  - name: phpmyadmin
    version: v2026.3.30
  updateConstraints:
    allowlist:
      groupReplication:
      - '>= 9.6.0'
      standalone:
      - '>= 9.6.0'
    denylist:
      groupReplication:
      - < 9.6.0
      standalone:
      - < 9.6.0
  version: 9.6.0
