apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  name: 5.7.42-debian
spec:
  archiver:
    addon:
      name: mysql-addon
      tasks:
        fullBackup:
          name: physical-backup
        fullBackupRestore:
          name: physical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
        volumeSnapshot:
          name: volume-snapshot
    walg:
      image: ghcr.io/kubedb/mysql-archiver:(v0.26.0-rc.2)_5.7.44
  coordinator:
    image: ghcr.io/kubedb/mysql-coordinator:v0.43.0-rc.2
  db:
    image: ghcr.io/appscode-images/mysql:5.7.42-debian
  distribution: Official
  endOfLife: true
  exporter:
    image: ghcr.io/kubedb/mysqld-exporter:v0.18.0
  gitSyncer:
    image: registry.k8s.io/git-sync/git-sync:v4.4.2
  initContainer:
    image: ghcr.io/kubedb/mysql-init:5.7-v9
  migrator:
    cli:
      image: ghcr.io/kubedb/mysql-migrator-cli:v0.5.0-rc.2
    statusReporter:
      image: ghcr.io/kubedb/migrator-operator:v0.5.0-rc.2
  podSecurityPolicies:
    databasePolicyName: mysql-db
  replicationModeDetector:
    image: ghcr.io/kubedb/replication-mode-detector:v0.52.0-rc.2
  securityContext:
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: mysql-backup-5.7.25
      restoreTask:
        name: mysql-restore-5.7.25
  ui:
  - name: phpmyadmin
    version: v2026.3.30
  updateConstraints:
    allowlist:
      groupReplication:
      - '>= 5.7.42, <= 8.0.36'
      standalone:
      - '>= 5.7.42, <= 8.0.36'
    denylist:
      groupReplication:
      - < 5.7.42
      standalone:
      - < 5.7.42
  version: 5.7.42
