---
# Source: kubedb/charts/petset/templates/webhook-server/monitoring/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubedb-petset
  namespace: kubedb
  labels:
    helm.sh/chart: petset-v2024.9.30
    app.kubernetes.io/name: petset
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: webhook-server
    app.kubernetes.io/name: petset
    app.kubernetes.io/instance: kubedb
