apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: kubedbmanifest-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  image: ghcr.io/shuvokumarmondal/kubedb-manifest-plugin:v1.0
