{{- if and (eq "prometheus.io/operator" ( include "monitoring.agent" . )) (not (lookup "v1" "Secret" .Release.Namespace (printf "%s-metrics-token" (include "kubedb-provider-aws.fullname" .)))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-metrics-token" (include "kubedb-provider-aws.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubedb-provider-aws.serviceAccountName" . }}
  labels:
    {{- include "kubedb-provider-aws.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
