---
# Source: kubedb/charts/petset/templates/rbac/cluster_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-petset
  labels:
    helm.sh/chart: petset-v2024.9.30
    app.kubernetes.io/name: petset
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.0.7"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedb-petset
subjects:
- kind: ServiceAccount
  name: kubedb-petset
  namespace: kubedb
