{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and .Values.oracle.enabled (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'oracle-differential-backup'
  labels:
    {{- include "kubedb-kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - differential-backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --target-pod=${targetPod:=}
  - --interval=${interval:=3600}
  image: '{{ include "image.dockerHub" (merge (dict "_repo" "sadi74/oracle-backup-plugin") $) }}:diff-test2{{ include "catalog.ubi" $ }}'
{{ end }}
