{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and .Values.oracle.enabled (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'oracle-restore'
  labels:
    {{- include "kubedb-kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - performRestore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --snapshot=${snapshot:=}
  - --until-time=${untilTime:=}
  - --until-scn=${untilSCN:=}
  - --restore-spfile=${restoreSPFile:=false}
  - --recover-to-latest=${recoverToLatest:=false}
  - --allow-autobackup-search=${allowAutobackupSearch:=false}
  image: '{{ include "image.dockerHub" (merge (dict "_repo" "sadi74/oracle-backup-plugin") $) }}:xrestore3{{ include "catalog.ubi" $ }}'
{{ end }}
