apiVersion: catalog.kubedb.com/v1alpha1
kind: AerospikeVersion
metadata:
  name: 8.1.2.2
spec:
  db:
    image: aerospike:ce-8.1.2.2
  securityContext:
    runAsUser: 999
  updateConstraints:
    allowlist:
    - 8.1.2.2
  version: 8.1.2.2
