apiVersion: catalog.kubedb.com/v1alpha1
kind: WeaviateVersion
metadata:
  name: 1.37.12
spec:
  db:
    image: ghcr.io/appscode-images/weaviate:1.37.12
  securityContext:
    runAsUser: 1000
  version: 1.37.12