#!/bin/bash

# Copyright AppsCode Inc. and Contributors
#
# Licensed under the AppsCode Community License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x

if [ -z "${IMAGE_REGISTRY}" ]; then
    echo "IMAGE_REGISTRY is not set"
    exit 1
fi

TARBALL=${1:-}
tar -zxvf $TARBALL

k3s ctr images import images/apicurio-apicurio-registry-kafkasql-2.5.11.Final.tar
k3s ctr images import images/apicurio-apicurio-registry-mem-2.5.11.Final.tar
k3s ctr images import images/clickhouse-clickhouse-keeper-24.4.1.tar
k3s ctr images import images/clickhouse-clickhouse-server-24.4.1.tar
k3s ctr images import images/floragunncom-sg-elasticsearch-7.9.3-oss-47.1.0.tar
k3s ctr images import images/aiven-open-karapace-3.15.0.tar
k3s ctr images import images/appscode-images-cassandra-exporter-2.3.8.tar
k3s ctr images import images/appscode-images-cassandra-4.1.6.tar
k3s ctr images import images/appscode-images-cassandra-5.0.0.tar
k3s ctr images import images/appscode-images-druid-28.0.1.tar
k3s ctr images import images/appscode-images-druid-30.0.1.tar
k3s ctr images import images/appscode-images-druid-31.0.0.tar
k3s ctr images import images/appscode-images-elastic-6.8.23.tar
k3s ctr images import images/appscode-images-elastic-7.13.4.tar
k3s ctr images import images/appscode-images-elastic-7.14.2.tar
k3s ctr images import images/appscode-images-elastic-7.16.3.tar
k3s ctr images import images/appscode-images-elastic-7.17.15.tar
k3s ctr images import images/appscode-images-elastic-7.17.23.tar
k3s ctr images import images/appscode-images-elastic-7.17.25.tar
k3s ctr images import images/appscode-images-elastic-8.11.1.tar
k3s ctr images import images/appscode-images-elastic-8.11.4.tar
k3s ctr images import images/appscode-images-elastic-8.13.4.tar
k3s ctr images import images/appscode-images-elastic-8.14.1.tar
k3s ctr images import images/appscode-images-elastic-8.14.3.tar
k3s ctr images import images/appscode-images-elastic-8.15.0.tar
k3s ctr images import images/appscode-images-elastic-8.15.4.tar
k3s ctr images import images/appscode-images-elastic-8.16.0.tar
k3s ctr images import images/appscode-images-elastic-8.2.3.tar
k3s ctr images import images/appscode-images-elastic-8.5.3.tar
k3s ctr images import images/appscode-images-elastic-8.6.2.tar
k3s ctr images import images/appscode-images-elastic-8.8.2.tar
k3s ctr images import images/appscode-images-ferretdb-1.18.0.tar
k3s ctr images import images/appscode-images-ferretdb-1.23.0.tar
k3s ctr images import images/appscode-images-ferretdb-1.24.0.tar
k3s ctr images import images/appscode-images-kafka-connect-cluster-3.5.2.tar
k3s ctr images import images/appscode-images-kafka-connect-cluster-3.6.1.tar
k3s ctr images import images/appscode-images-kafka-connect-cluster-3.7.2.tar
k3s ctr images import images/appscode-images-kafka-connect-cluster-3.8.1.tar
k3s ctr images import images/appscode-images-kafka-connect-cluster-3.9.0.tar
k3s ctr images import images/appscode-images-kafka-connector-gcs-0.13.0.tar
k3s ctr images import images/appscode-images-kafka-connector-jdbc-2.6.1.final.tar
k3s ctr images import images/appscode-images-kafka-connector-jdbc-2.7.4.final.tar
k3s ctr images import images/appscode-images-kafka-connector-jdbc-3.0.5.final.tar
k3s ctr images import images/appscode-images-kafka-connector-mongodb-1.13.1.tar
k3s ctr images import images/appscode-images-kafka-connector-mongodb-1.14.1.tar
k3s ctr images import images/appscode-images-kafka-connector-mysql-2.7.4.final.tar
k3s ctr images import images/appscode-images-kafka-connector-mysql-3.0.5.final.tar
k3s ctr images import images/appscode-images-kafka-connector-postgres-2.7.4.final.tar
k3s ctr images import images/appscode-images-kafka-connector-postgres-3.0.5.final.tar
k3s ctr images import images/appscode-images-kafka-connector-s3-2.15.0.tar
k3s ctr images import images/appscode-images-kafka-cruise-control-3.5.2.tar
k3s ctr images import images/appscode-images-kafka-cruise-control-3.6.1.tar
k3s ctr images import images/appscode-images-kafka-cruise-control-3.7.2.tar
k3s ctr images import images/appscode-images-kafka-cruise-control-3.8.1.tar
k3s ctr images import images/appscode-images-kafka-cruise-control-3.9.0.tar
k3s ctr images import images/appscode-images-kafka-kraft-3.5.2.tar
k3s ctr images import images/appscode-images-kafka-kraft-3.6.1.tar
k3s ctr images import images/appscode-images-kafka-kraft-3.7.2.tar
k3s ctr images import images/appscode-images-kafka-kraft-3.8.1.tar
k3s ctr images import images/appscode-images-kafka-kraft-3.9.0.tar
k3s ctr images import images/appscode-images-kibana-6.8.23.tar
k3s ctr images import images/appscode-images-kibana-7.13.4.tar
k3s ctr images import images/appscode-images-kibana-7.14.2.tar
k3s ctr images import images/appscode-images-kibana-7.16.3.tar
k3s ctr images import images/appscode-images-kibana-7.17.15.tar
k3s ctr images import images/appscode-images-kibana-7.17.23.tar
k3s ctr images import images/appscode-images-kibana-7.17.25.tar
k3s ctr images import images/appscode-images-kibana-8.11.1.tar
k3s ctr images import images/appscode-images-kibana-8.11.4.tar
k3s ctr images import images/appscode-images-kibana-8.13.4.tar
k3s ctr images import images/appscode-images-kibana-8.14.1.tar
k3s ctr images import images/appscode-images-kibana-8.14.3.tar
k3s ctr images import images/appscode-images-kibana-8.15.0.tar
k3s ctr images import images/appscode-images-kibana-8.15.4.tar
k3s ctr images import images/appscode-images-kibana-8.16.0.tar
k3s ctr images import images/appscode-images-kibana-8.2.3.tar
k3s ctr images import images/appscode-images-kibana-8.5.3.tar
k3s ctr images import images/appscode-images-kibana-8.6.2.tar
k3s ctr images import images/appscode-images-kibana-8.8.2.tar
k3s ctr images import images/appscode-images-mariadb-10.10.7-jammy.tar
k3s ctr images import images/appscode-images-mariadb-10.11.6-jammy.tar
k3s ctr images import images/appscode-images-mariadb-10.4.32-focal.tar
k3s ctr images import images/appscode-images-mariadb-10.5.23-focal.tar
k3s ctr images import images/appscode-images-mariadb-10.6.16-focal.tar
k3s ctr images import images/appscode-images-mariadb-11.0.4-jammy.tar
k3s ctr images import images/appscode-images-mariadb-11.1.3-jammy.tar
k3s ctr images import images/appscode-images-mariadb-11.2.2-jammy.tar
k3s ctr images import images/appscode-images-mariadb-11.3.2-jammy.tar
k3s ctr images import images/appscode-images-mariadb-11.4.3-noble.tar
k3s ctr images import images/appscode-images-mariadb-11.5.2-noble.tar
k3s ctr images import images/appscode-images-mariadb-11.6.2-noble.tar
k3s ctr images import images/appscode-images-memcached-1.5.22-alpine.tar
k3s ctr images import images/appscode-images-memcached-1.6.22-alpine.tar
k3s ctr images import images/appscode-images-memcached-1.6.29-alpine.tar
k3s ctr images import images/appscode-images-memcached-1.6.33-alpine.tar
k3s ctr images import images/appscode-images-memcached_exporter-v0.14.3-ac.tar
k3s ctr images import images/appscode-images-mongo-4.2.24.tar
k3s ctr images import images/appscode-images-mongo-4.4.26.tar
k3s ctr images import images/appscode-images-mongo-5.0.23.tar
k3s ctr images import images/appscode-images-mongo-5.0.26.tar
k3s ctr images import images/appscode-images-mongo-6.0.12.tar
k3s ctr images import images/appscode-images-mongo-7.0.16.tar
k3s ctr images import images/appscode-images-mongo-7.0.5.tar
k3s ctr images import images/appscode-images-mongo-7.0.8.tar
k3s ctr images import images/appscode-images-mongo-8.0.4.tar
k3s ctr images import images/appscode-images-mysql-5.7.42-debian.tar
k3s ctr images import images/appscode-images-mysql-5.7.44-oracle.tar
k3s ctr images import images/appscode-images-mysql-8.0.31-oracle.tar
k3s ctr images import images/appscode-images-mysql-8.0.35-oracle.tar
k3s ctr images import images/appscode-images-mysql-8.0.36-debian.tar
k3s ctr images import images/appscode-images-mysql-8.1.0-oracle.tar
k3s ctr images import images/appscode-images-mysql-8.2.0-oracle.tar
k3s ctr images import images/appscode-images-mysql-8.4.2-oracle.tar
k3s ctr images import images/appscode-images-mysql-8.4.3-oracle.tar
k3s ctr images import images/appscode-images-mysql-9.0.1-oracle.tar
k3s ctr images import images/appscode-images-mysql-9.1.0-oracle.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-1.1.0.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-1.2.0.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-1.3.13.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-1.3.18.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-1.3.19.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.0.1.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.11.1.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.14.0.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.16.0.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.17.1.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.18.0.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.5.0.tar
k3s ctr images import images/appscode-images-opensearch-dashboards-2.8.0.tar
k3s ctr images import images/appscode-images-opensearch-1.1.0.tar
k3s ctr images import images/appscode-images-opensearch-1.2.4.tar
k3s ctr images import images/appscode-images-opensearch-1.3.13.tar
k3s ctr images import images/appscode-images-opensearch-1.3.18.tar
k3s ctr images import images/appscode-images-opensearch-1.3.19.tar
k3s ctr images import images/appscode-images-opensearch-2.0.1.tar
k3s ctr images import images/appscode-images-opensearch-2.11.1.tar
k3s ctr images import images/appscode-images-opensearch-2.14.0.tar
k3s ctr images import images/appscode-images-opensearch-2.16.0.tar
k3s ctr images import images/appscode-images-opensearch-2.17.1.tar
k3s ctr images import images/appscode-images-opensearch-2.18.0.tar
k3s ctr images import images/appscode-images-opensearch-2.5.0.tar
k3s ctr images import images/appscode-images-opensearch-2.8.0.tar
k3s ctr images import images/appscode-images-percona-xtradb-cluster-5.7.44.tar
k3s ctr images import images/appscode-images-percona-xtradb-cluster-8.0.40.tar
k3s ctr images import images/appscode-images-percona-xtradb-cluster-8.4.3.tar
k3s ctr images import images/appscode-images-pgpool2-4.4.5.tar
k3s ctr images import images/appscode-images-pgpool2-4.4.8.tar
k3s ctr images import images/appscode-images-pgpool2-4.5.0.tar
k3s ctr images import images/appscode-images-pgpool2-4.5.3.tar
k3s ctr images import images/appscode-images-pgpool2_exporter-v1.2.2.tar
k3s ctr images import images/appscode-images-postgres-10.23-alpine.tar
k3s ctr images import images/appscode-images-postgres-10.23-bullseye.tar
k3s ctr images import images/appscode-images-postgres-11.22-alpine.tar
k3s ctr images import images/appscode-images-postgres-11.22-bookworm.tar
k3s ctr images import images/appscode-images-postgres-12.17-alpine.tar
k3s ctr images import images/appscode-images-postgres-12.17-bookworm.tar
k3s ctr images import images/appscode-images-postgres-12.22-alpine.tar
k3s ctr images import images/appscode-images-postgres-12.22-bookworm.tar
k3s ctr images import images/appscode-images-postgres-13.13-alpine.tar
k3s ctr images import images/appscode-images-postgres-13.13-bookworm.tar
k3s ctr images import images/appscode-images-postgres-13.18-alpine.tar
k3s ctr images import images/appscode-images-postgres-13.18-bookworm.tar
k3s ctr images import images/appscode-images-postgres-14.10-alpine.tar
k3s ctr images import images/appscode-images-postgres-14.10-bookworm.tar
k3s ctr images import images/appscode-images-postgres-14.13-alpine.tar
k3s ctr images import images/appscode-images-postgres-14.13-bookworm.tar
k3s ctr images import images/appscode-images-postgres-14.15-alpine.tar
k3s ctr images import images/appscode-images-postgres-14.15-bookworm.tar
k3s ctr images import images/appscode-images-postgres-15.10-alpine.tar
k3s ctr images import images/appscode-images-postgres-15.10-bookworm.tar
k3s ctr images import images/appscode-images-postgres-15.5-alpine.tar
k3s ctr images import images/appscode-images-postgres-15.5-bookworm.tar
k3s ctr images import images/appscode-images-postgres-15.8-alpine.tar
k3s ctr images import images/appscode-images-postgres-15.8-bookworm.tar
k3s ctr images import images/appscode-images-postgres-16.1-alpine.tar
k3s ctr images import images/appscode-images-postgres-16.1-bookworm.tar
k3s ctr images import images/appscode-images-postgres-16.4-alpine.tar
k3s ctr images import images/appscode-images-postgres-16.4-bookworm.tar
k3s ctr images import images/appscode-images-postgres-16.6-alpine.tar
k3s ctr images import images/appscode-images-postgres-16.6-bookworm.tar
k3s ctr images import images/appscode-images-postgres-17.2-alpine.tar
k3s ctr images import images/appscode-images-postgres-17.2-bookworm.tar
k3s ctr images import images/appscode-images-rabbitmq-3.12.12-management-alpine.tar
k3s ctr images import images/appscode-images-rabbitmq-3.13.2-management-alpine.tar
k3s ctr images import images/appscode-images-rabbitmq-4.0.4-management-alpine.tar
k3s ctr images import images/appscode-images-redis-5.0.14-bullseye.tar
k3s ctr images import images/appscode-images-redis-6.0.20-bookworm.tar
k3s ctr images import images/appscode-images-redis-6.2.14-bookworm.tar
k3s ctr images import images/appscode-images-redis-6.2.16-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.0.14-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.0.15-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.2.3-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.2.4-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.2.6-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.4.0-bookworm.tar
k3s ctr images import images/appscode-images-redis-7.4.1-bookworm.tar
k3s ctr images import images/appscode-images-singlestore-node-alma-8.1.32-e3d3cde6da.tar
k3s ctr images import images/appscode-images-singlestore-node-alma-8.5.30-4f46ab16a5.tar
k3s ctr images import images/appscode-images-singlestore-node-alma-8.5.7-bf633c1a54.tar
k3s ctr images import images/appscode-images-singlestore-node-alma-8.7.10-95e2357384.tar
k3s ctr images import images/appscode-images-singlestore-node-alma-8.7.21-f0b8de04d5.tar
k3s ctr images import images/appscode-images-singlestore-node-alma-8.9.3-bfa36a984a.tar
k3s ctr images import images/appscode-images-solr-8.11.4.tar
k3s ctr images import images/appscode-images-solr-9.4.1.tar
k3s ctr images import images/appscode-images-solr-9.6.1.tar
k3s ctr images import images/appscode-images-solr-9.7.0.tar
k3s ctr images import images/appscode-images-zookeeper-3.7.2.tar
k3s ctr images import images/appscode-images-zookeeper-3.8.3.tar
k3s ctr images import images/appscode-images-zookeeper-3.9.1.tar
k3s ctr images import images/appscode-kube-rbac-proxy-v0.15.0.tar
k3s ctr images import images/appscode-kubectl-nonroot-1.31.tar
k3s ctr images import images/appscode-petset-v0.0.7.tar
k3s ctr images import images/appscode-sidekick-v0.0.10.tar
k3s ctr images import images/kubedb-cassandra-init-4.1.6-v1.tar
k3s ctr images import images/kubedb-cassandra-init-5.0.0-v1.tar
k3s ctr images import images/kubedb-clickhouse-init-24.4.1.tar
k3s ctr images import images/kubedb-dashboard-restic-plugin-v0.1.0.tar
k3s ctr images import images/kubedb-dashboard-restic-plugin-v0.10.0.tar
k3s ctr images import images/kubedb-druid-init-28.0.1.tar
k3s ctr images import images/kubedb-druid-init-30.0.1.tar
k3s ctr images import images/kubedb-druid-init-31.0.0.tar
k3s ctr images import images/kubedb-elasticsearch-restic-plugin-v0.15.0.tar
k3s ctr images import images/kubedb-kubedb-autoscaler-v0.37.0.tar
k3s ctr images import images/kubedb-kubedb-crd-manager-v0.7.0.tar
k3s ctr images import images/kubedb-kubedb-gitops-v0.0.1.tar
k3s ctr images import images/kubedb-kubedb-kibana-v0.28.0.tar
k3s ctr images import images/kubedb-kubedb-manifest-plugin-v0.15.0.tar
k3s ctr images import images/kubedb-kubedb-ops-manager-v0.39.0.tar
k3s ctr images import images/kubedb-kubedb-provisioner-v0.52.0.tar
k3s ctr images import images/kubedb-kubedb-schema-manager-v0.28.0.tar
k3s ctr images import images/kubedb-kubedb-ui-server-v0.28.0.tar
k3s ctr images import images/kubedb-kubedb-verifier-v0.1.0.tar
k3s ctr images import images/kubedb-kubedb-webhook-server-v0.28.0.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_10.10.7-jammy.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_10.11.6-jammy.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_10.4.32-focal.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_10.5.23-focal.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_10.6.16-focal.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_11.0.4-jammy.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_11.1.3-jammy.tar
k3s ctr images import images/kubedb-mariadb-archiver-v0.12.0_11.2.2-jammy.tar
k3s ctr images import images/kubedb-mariadb-coordinator-v0.32.0.tar
k3s ctr images import images/kubedb-mariadb-csi-snapshotter-plugin-v0.12.0.tar
k3s ctr images import images/kubedb-mariadb-init-0.5.2.tar
k3s ctr images import images/kubedb-mariadb-restic-plugin-v0.10.0.tar
k3s ctr images import images/kubedb-mongodb-csi-snapshotter-plugin-v0.13.0.tar
k3s ctr images import images/kubedb-mongodb-init-4.2-v9.tar
k3s ctr images import images/kubedb-mongodb-init-6.0-v10.tar
k3s ctr images import images/kubedb-mongodb_exporter-v0.40.0.tar
k3s ctr images import images/kubedb-mssql-coordinator-v0.7.0.tar
k3s ctr images import images/kubedb-mssql-exporter-1.1.0.tar
k3s ctr images import images/kubedb-mssql-init-2022-ubuntu-22-v3.tar
k3s ctr images import images/kubedb-mssqlserver-archiver-v0.6.0.tar
k3s ctr images import images/kubedb-mssqlserver-walg-plugin-v0.0.1.tar
k3s ctr images import images/kubedb-mysql-archiver-v0.13.0_5.7.44.tar
k3s ctr images import images/kubedb-mysql-archiver-v0.13.0_8.0.35.tar
k3s ctr images import images/kubedb-mysql-archiver-v0.13.0_8.1.0.tar
k3s ctr images import images/kubedb-mysql-archiver-v0.13.0_8.2.0.tar
k3s ctr images import images/kubedb-mysql-archiver-v0.13.0_8.4.3.tar
k3s ctr images import images/kubedb-mysql-archiver-v0.13.0_9.1.0.tar
k3s ctr images import images/kubedb-mysql-coordinator-v0.30.0.tar
k3s ctr images import images/kubedb-mysql-csi-snapshotter-plugin-v0.13.0.tar
k3s ctr images import images/kubedb-mysql-init-5.7-v5.tar
k3s ctr images import images/kubedb-mysql-init-8.0.31-v4.tar
k3s ctr images import images/kubedb-mysql-init-8.4.2-v3.tar
k3s ctr images import images/kubedb-mysql-init-8.4.3-v3.tar
k3s ctr images import images/kubedb-mysql-init-9.0.1-v1.tar
k3s ctr images import images/kubedb-mysql-init-9.1.0-v1.tar
k3s ctr images import images/kubedb-mysql-router-init-v0.30.0.tar
k3s ctr images import images/kubedb-mysqld-exporter-v0.13.1.tar
k3s ctr images import images/kubedb-percona-xtradb-coordinator-v0.25.0.tar
k3s ctr images import images/kubedb-percona-xtradb-init-0.2.3.tar
k3s ctr images import images/kubedb-pg-coordinator-v0.36.0.tar
k3s ctr images import images/kubedb-pgbouncer-1.17.0.tar
k3s ctr images import images/kubedb-pgbouncer-1.18.0.tar
k3s ctr images import images/kubedb-pgbouncer-1.23.1.tar
k3s ctr images import images/kubedb-pgbouncer-1.24.0.tar
k3s ctr images import images/kubedb-pgbouncer_exporter-v0.1.1.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_11.22-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_11.22-bookworm.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_12.17-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_12.17-bookworm.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_13.13-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_13.13-bookworm.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_14.10-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_14.10-bookworm.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_15.5-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_15.5-bookworm.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_16.1-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_16.1-bookworm.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_17.2-alpine.tar
k3s ctr images import images/kubedb-postgres-archiver-v0.13.0_17.2-bookworm.tar
k3s ctr images import images/kubedb-postgres-csi-snapshotter-plugin-v0.13.0.tar
k3s ctr images import images/kubedb-postgres-init-0.17.1.tar
k3s ctr images import images/kubedb-postgres-restic-plugin-v0.15.0_16.1.tar
k3s ctr images import images/kubedb-provider-aws-v0.14.0.tar
k3s ctr images import images/kubedb-provider-azure-v0.14.0.tar
k3s ctr images import images/kubedb-provider-gcp-v0.14.0.tar
k3s ctr images import images/kubedb-proxysql-exporter-v1.1.0.tar
k3s ctr images import images/kubedb-proxysql-2.3.2-centos-v2.tar
k3s ctr images import images/kubedb-proxysql-2.3.2-debian-v2.tar
k3s ctr images import images/kubedb-proxysql-2.4.4-centos.tar
k3s ctr images import images/kubedb-proxysql-2.4.4-debian.tar
k3s ctr images import images/kubedb-proxysql-2.6.3-debian.tar
k3s ctr images import images/kubedb-rabbitmq-init-3.12.12.tar
k3s ctr images import images/kubedb-rabbitmq-init-3.13.2.tar
k3s ctr images import images/kubedb-rabbitmq-init-4.0.4.tar
k3s ctr images import images/kubedb-redis-coordinator-v0.31.0.tar
k3s ctr images import images/kubedb-redis-init-0.9.0.tar
k3s ctr images import images/kubedb-redis-restic-plugin-v0.15.0.tar
k3s ctr images import images/kubedb-redis-4.0.11.tar
k3s ctr images import images/kubedb-redis_exporter-1.66.0.tar
k3s ctr images import images/kubedb-replication-mode-detector-v0.39.0.tar
k3s ctr images import images/kubedb-singlestore-coordinator-v0.7.0.tar
k3s ctr images import images/kubedb-singlestore-init-8.1-v2.tar
k3s ctr images import images/kubedb-singlestore-init-8.5-v2.tar
k3s ctr images import images/kubedb-singlestore-init-8.7.10-v1.tar
k3s ctr images import images/kubedb-solr-init-8.11.4.tar
k3s ctr images import images/kubedb-solr-init-9.4.1.tar
k3s ctr images import images/kubedb-solr-init-9.6.1.tar
k3s ctr images import images/kubedb-solr-init-9.7.0.tar
k3s ctr images import images/kubedb-wal-g-v2024.12.18_mongo.tar
k3s ctr images import images/kubedb-zookeeper-init-3.7-v1.tar
k3s ctr images import images/kubedb-zookeeper-restic-plugin-v0.8.0.tar
k3s ctr images import images/mssql-server-2022-CU12-ubuntu-22.04.tar
k3s ctr images import images/mssql-server-2022-CU14-ubuntu-22.04.tar
k3s ctr images import images/mssql-server-2022-CU16-ubuntu-22.04.tar
k3s ctr images import images/mysql-mysql-router-8.0.31.tar
k3s ctr images import images/percona-percona-server-mongodb-4.2.24.tar
k3s ctr images import images/percona-percona-server-mongodb-4.4.26.tar
k3s ctr images import images/percona-percona-server-mongodb-5.0.23.tar
k3s ctr images import images/percona-percona-server-mongodb-6.0.12.tar
k3s ctr images import images/percona-percona-server-mongodb-7.0.4.tar
k3s ctr images import images/postgis-postgis-11-3.3.tar
k3s ctr images import images/postgis-postgis-12-3.4.tar
k3s ctr images import images/postgis-postgis-13-3.4.tar
k3s ctr images import images/postgis-postgis-14-3.4.tar
k3s ctr images import images/postgis-postgis-15-3.4.tar
k3s ctr images import images/postgis-postgis-16-3.4.tar
k3s ctr images import images/prom-memcached-exporter-v0.14.2.tar
k3s ctr images import images/prom-mysqld-exporter-v0.13.0.tar
k3s ctr images import images/prometheuscommunity-elasticsearch-exporter-v1.7.0.tar
k3s ctr images import images/prometheuscommunity-postgres-exporter-v0.15.0.tar
k3s ctr images import images/git-sync-git-sync-v4.2.1.tar
k3s ctr images import images/singlestore-cluster-in-a-box-alma-8.1.32-e3d3cde6da-4.0.16-1.17.6.tar
k3s ctr images import images/singlestore-cluster-in-a-box-alma-8.5.22-fe61f40cd1-4.1.0-1.17.11.tar
k3s ctr images import images/singlestore-cluster-in-a-box-alma-8.5.7-bf633c1a54-4.0.17-1.17.8.tar
k3s ctr images import images/singlestore-cluster-in-a-box-alma-8.7.10-95e2357384-4.1.0-1.17.14.tar
k3s ctr images import images/tianon-toybox-0.8.11.tar
k3s ctr images import images/timescale-timescaledb-2.14.2-pg13-oss.tar
k3s ctr images import images/timescale-timescaledb-2.14.2-pg14-oss.tar
k3s ctr images import images/timescale-timescaledb-2.14.2-pg15-oss.tar
k3s ctr images import images/timescale-timescaledb-2.14.2-pg16-oss.tar
