#!/bin/bash

# Copyright AppsCode Inc. and Contributors
#
# Licensed under the AppsCode Community License 1.0.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x

if [ -z "${IMAGE_REGISTRY}" ]; then
    echo "IMAGE_REGISTRY is not set"
    exit 1
fi

TARBALL=${1:-}
tar -zxvf $TARBALL

CMD="./crane"

$CMD push --allow-nondistributable-artifacts --insecure images/apicurio-apicurio-registry-kafkasql-2.5.11.Final.tar $IMAGE_REGISTRY/apicurio/apicurio-registry-kafkasql:2.5.11.Final
$CMD push --allow-nondistributable-artifacts --insecure images/apicurio-apicurio-registry-mem-2.5.11.Final.tar $IMAGE_REGISTRY/apicurio/apicurio-registry-mem:2.5.11.Final
$CMD push --allow-nondistributable-artifacts --insecure images/library-busybox-1.36.tar $IMAGE_REGISTRY/busybox:1.36
$CMD push --allow-nondistributable-artifacts --insecure images/clickhouse-clickhouse-keeper-24.4.1.tar $IMAGE_REGISTRY/clickhouse/clickhouse-keeper:24.4.1
$CMD push --allow-nondistributable-artifacts --insecure images/clickhouse-clickhouse-keeper-25.7.1.tar $IMAGE_REGISTRY/clickhouse/clickhouse-keeper:25.7.1
$CMD push --allow-nondistributable-artifacts --insecure images/clickhouse-clickhouse-server-24.4.1.tar $IMAGE_REGISTRY/clickhouse/clickhouse-server:24.4.1
$CMD push --allow-nondistributable-artifacts --insecure images/clickhouse-clickhouse-server-25.7.1.tar $IMAGE_REGISTRY/clickhouse/clickhouse-server:25.7.1
$CMD push --allow-nondistributable-artifacts --insecure images/floragunncom-sg-elasticsearch-7.9.3-oss-47.1.0.tar $IMAGE_REGISTRY/floragunncom/sg-elasticsearch:7.9.3-oss-47.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/aiven-open-karapace-3.15.0.tar $IMAGE_REGISTRY/aiven-open/karapace:3.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-cassandra-exporter-2.3.8.tar $IMAGE_REGISTRY/appscode-images/cassandra-exporter:2.3.8
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-cassandra-management-4.1.8.tar $IMAGE_REGISTRY/appscode-images/cassandra-management:4.1.8
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-cassandra-management-5.0.3.tar $IMAGE_REGISTRY/appscode-images/cassandra-management:5.0.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-cassandra-medusa-0.24.0.tar $IMAGE_REGISTRY/appscode-images/cassandra-medusa:0.24.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-druid-28.0.1.tar $IMAGE_REGISTRY/appscode-images/druid:28.0.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-druid-30.0.1.tar $IMAGE_REGISTRY/appscode-images/druid:30.0.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-druid-31.0.0.tar $IMAGE_REGISTRY/appscode-images/druid:31.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-6.8.23.tar $IMAGE_REGISTRY/appscode-images/elastic:6.8.23
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.13.4.tar $IMAGE_REGISTRY/appscode-images/elastic:7.13.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.14.2.tar $IMAGE_REGISTRY/appscode-images/elastic:7.14.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.16.3.tar $IMAGE_REGISTRY/appscode-images/elastic:7.16.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.17.15.tar $IMAGE_REGISTRY/appscode-images/elastic:7.17.15
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.17.23.tar $IMAGE_REGISTRY/appscode-images/elastic:7.17.23
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.17.25.tar $IMAGE_REGISTRY/appscode-images/elastic:7.17.25
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.17.27.tar $IMAGE_REGISTRY/appscode-images/elastic:7.17.27
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-7.17.28.tar $IMAGE_REGISTRY/appscode-images/elastic:7.17.28
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.11.1.tar $IMAGE_REGISTRY/appscode-images/elastic:8.11.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.11.4.tar $IMAGE_REGISTRY/appscode-images/elastic:8.11.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.13.4.tar $IMAGE_REGISTRY/appscode-images/elastic:8.13.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.14.1.tar $IMAGE_REGISTRY/appscode-images/elastic:8.14.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.14.3.tar $IMAGE_REGISTRY/appscode-images/elastic:8.14.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.15.0.tar $IMAGE_REGISTRY/appscode-images/elastic:8.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.15.4.tar $IMAGE_REGISTRY/appscode-images/elastic:8.15.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.16.0.tar $IMAGE_REGISTRY/appscode-images/elastic:8.16.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.16.4.tar $IMAGE_REGISTRY/appscode-images/elastic:8.16.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.17.2.tar $IMAGE_REGISTRY/appscode-images/elastic:8.17.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.17.6.tar $IMAGE_REGISTRY/appscode-images/elastic:8.17.6
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.18.2.tar $IMAGE_REGISTRY/appscode-images/elastic:8.18.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.2.3.tar $IMAGE_REGISTRY/appscode-images/elastic:8.2.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.5.3.tar $IMAGE_REGISTRY/appscode-images/elastic:8.5.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.6.2.tar $IMAGE_REGISTRY/appscode-images/elastic:8.6.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-8.8.2.tar $IMAGE_REGISTRY/appscode-images/elastic:8.8.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-elastic-9.0.2.tar $IMAGE_REGISTRY/appscode-images/elastic:9.0.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-ferretdb-1.18.0.tar $IMAGE_REGISTRY/appscode-images/ferretdb:1.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-ferretdb-1.23.0.tar $IMAGE_REGISTRY/appscode-images/ferretdb:1.23.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-ferretdb-1.24.0.tar $IMAGE_REGISTRY/appscode-images/ferretdb:1.24.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-ferretdb-2.0.0.tar $IMAGE_REGISTRY/appscode-images/ferretdb:2.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-ignite-2.17.0.tar $IMAGE_REGISTRY/appscode-images/ignite:2.17.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connect-cluster-3.5.2.tar $IMAGE_REGISTRY/appscode-images/kafka-connect-cluster:3.5.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connect-cluster-3.6.1.tar $IMAGE_REGISTRY/appscode-images/kafka-connect-cluster:3.6.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connect-cluster-3.7.2.tar $IMAGE_REGISTRY/appscode-images/kafka-connect-cluster:3.7.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connect-cluster-3.8.1.tar $IMAGE_REGISTRY/appscode-images/kafka-connect-cluster:3.8.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connect-cluster-3.9.0.tar $IMAGE_REGISTRY/appscode-images/kafka-connect-cluster:3.9.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connect-cluster-4.0.0.tar $IMAGE_REGISTRY/appscode-images/kafka-connect-cluster:4.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-gcs-0.13.0.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-gcs:0.13.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-jdbc-2.6.1.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-jdbc:2.6.1.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-jdbc-2.7.4.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-jdbc:2.7.4.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-jdbc-3.0.5.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-jdbc:3.0.5.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-mongodb-1.13.1.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-mongodb:1.13.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-mongodb-1.14.1.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-mongodb:1.14.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-mysql-2.7.4.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-mysql:2.7.4.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-mysql-3.0.5.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-mysql:3.0.5.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-postgres-2.7.4.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-postgres:2.7.4.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-postgres-3.0.5.final.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-postgres:3.0.5.final
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-connector-s3-2.15.0.tar $IMAGE_REGISTRY/appscode-images/kafka-connector-s3:2.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-cruise-control-3.5.2.tar $IMAGE_REGISTRY/appscode-images/kafka-cruise-control:3.5.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-cruise-control-3.6.1.tar $IMAGE_REGISTRY/appscode-images/kafka-cruise-control:3.6.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-cruise-control-3.7.2.tar $IMAGE_REGISTRY/appscode-images/kafka-cruise-control:3.7.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-cruise-control-3.8.1.tar $IMAGE_REGISTRY/appscode-images/kafka-cruise-control:3.8.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-cruise-control-3.9.0.tar $IMAGE_REGISTRY/appscode-images/kafka-cruise-control:3.9.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-cruise-control-4.0.0.tar $IMAGE_REGISTRY/appscode-images/kafka-cruise-control:4.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-kraft-3.5.2.tar $IMAGE_REGISTRY/appscode-images/kafka-kraft:3.5.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-kraft-3.6.1.tar $IMAGE_REGISTRY/appscode-images/kafka-kraft:3.6.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-kraft-3.7.2.tar $IMAGE_REGISTRY/appscode-images/kafka-kraft:3.7.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-kraft-3.8.1.tar $IMAGE_REGISTRY/appscode-images/kafka-kraft:3.8.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-kraft-3.9.0.tar $IMAGE_REGISTRY/appscode-images/kafka-kraft:3.9.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kafka-4.0.0.tar $IMAGE_REGISTRY/appscode-images/kafka:4.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-6.8.23.tar $IMAGE_REGISTRY/appscode-images/kibana:6.8.23
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.13.4.tar $IMAGE_REGISTRY/appscode-images/kibana:7.13.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.14.2.tar $IMAGE_REGISTRY/appscode-images/kibana:7.14.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.16.3.tar $IMAGE_REGISTRY/appscode-images/kibana:7.16.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.17.15.tar $IMAGE_REGISTRY/appscode-images/kibana:7.17.15
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.17.23.tar $IMAGE_REGISTRY/appscode-images/kibana:7.17.23
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.17.25.tar $IMAGE_REGISTRY/appscode-images/kibana:7.17.25
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.17.27.tar $IMAGE_REGISTRY/appscode-images/kibana:7.17.27
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-7.17.28.tar $IMAGE_REGISTRY/appscode-images/kibana:7.17.28
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.11.1.tar $IMAGE_REGISTRY/appscode-images/kibana:8.11.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.11.4.tar $IMAGE_REGISTRY/appscode-images/kibana:8.11.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.13.4.tar $IMAGE_REGISTRY/appscode-images/kibana:8.13.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.14.1.tar $IMAGE_REGISTRY/appscode-images/kibana:8.14.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.14.3.tar $IMAGE_REGISTRY/appscode-images/kibana:8.14.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.15.0.tar $IMAGE_REGISTRY/appscode-images/kibana:8.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.15.4.tar $IMAGE_REGISTRY/appscode-images/kibana:8.15.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.16.0.tar $IMAGE_REGISTRY/appscode-images/kibana:8.16.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.16.4.tar $IMAGE_REGISTRY/appscode-images/kibana:8.16.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.17.2.tar $IMAGE_REGISTRY/appscode-images/kibana:8.17.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.17.6.tar $IMAGE_REGISTRY/appscode-images/kibana:8.17.6
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.18.2.tar $IMAGE_REGISTRY/appscode-images/kibana:8.18.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.2.3.tar $IMAGE_REGISTRY/appscode-images/kibana:8.2.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.5.3.tar $IMAGE_REGISTRY/appscode-images/kibana:8.5.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.6.2.tar $IMAGE_REGISTRY/appscode-images/kibana:8.6.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-8.8.2.tar $IMAGE_REGISTRY/appscode-images/kibana:8.8.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-kibana-9.0.2.tar $IMAGE_REGISTRY/appscode-images/kibana:9.0.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-10.10.7-jammy.tar $IMAGE_REGISTRY/appscode-images/mariadb:10.10.7-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-10.11.6-jammy.tar $IMAGE_REGISTRY/appscode-images/mariadb:10.11.6-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-10.4.32-focal.tar $IMAGE_REGISTRY/appscode-images/mariadb:10.4.32-focal
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-10.5.23-focal.tar $IMAGE_REGISTRY/appscode-images/mariadb:10.5.23-focal
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-10.6.16-focal.tar $IMAGE_REGISTRY/appscode-images/mariadb:10.6.16-focal
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.0.4-jammy.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.0.4-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.1.3-jammy.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.1.3-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.2.2-jammy.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.2.2-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.3.2-jammy.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.3.2-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.4.3-noble.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.4.3-noble
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.5.2-noble.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.5.2-noble
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mariadb-11.6.2-noble.tar $IMAGE_REGISTRY/appscode-images/mariadb:11.6.2-noble
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-memcached-1.5.22-alpine.tar $IMAGE_REGISTRY/appscode-images/memcached:1.5.22-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-memcached-1.6.22-alpine.tar $IMAGE_REGISTRY/appscode-images/memcached:1.6.22-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-memcached-1.6.29-alpine.tar $IMAGE_REGISTRY/appscode-images/memcached:1.6.29-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-memcached-1.6.33-alpine.tar $IMAGE_REGISTRY/appscode-images/memcached:1.6.33-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-memcached_exporter-v0.14.3-ac.tar $IMAGE_REGISTRY/appscode-images/memcached_exporter:v0.14.3-ac
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-4.2.24.tar $IMAGE_REGISTRY/appscode-images/mongo:4.2.24
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-4.4.26.tar $IMAGE_REGISTRY/appscode-images/mongo:4.4.26
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-5.0.23.tar $IMAGE_REGISTRY/appscode-images/mongo:5.0.23
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-5.0.26.tar $IMAGE_REGISTRY/appscode-images/mongo:5.0.26
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-5.0.31.tar $IMAGE_REGISTRY/appscode-images/mongo:5.0.31
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-6.0.12.tar $IMAGE_REGISTRY/appscode-images/mongo:6.0.12
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-6.0.24.tar $IMAGE_REGISTRY/appscode-images/mongo:6.0.24
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-7.0.16.tar $IMAGE_REGISTRY/appscode-images/mongo:7.0.16
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-7.0.21.tar $IMAGE_REGISTRY/appscode-images/mongo:7.0.21
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-7.0.5.tar $IMAGE_REGISTRY/appscode-images/mongo:7.0.5
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-7.0.8.tar $IMAGE_REGISTRY/appscode-images/mongo:7.0.8
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-8.0.10.tar $IMAGE_REGISTRY/appscode-images/mongo:8.0.10
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mongo-8.0.4.tar $IMAGE_REGISTRY/appscode-images/mongo:8.0.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-5.7.42-debian.tar $IMAGE_REGISTRY/appscode-images/mysql:5.7.42-debian
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-5.7.44-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:5.7.44-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.0.31-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:8.0.31-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.0.35-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:8.0.35-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.0.36-debian.tar $IMAGE_REGISTRY/appscode-images/mysql:8.0.36-debian
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.1.0-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:8.1.0-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.2.0-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:8.2.0-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.4.2-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:8.4.2-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-8.4.3-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:8.4.3-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-9.0.1-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:9.0.1-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-mysql-9.1.0-oracle.tar $IMAGE_REGISTRY/appscode-images/mysql:9.1.0-oracle
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-1.1.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:1.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-1.2.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:1.2.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-1.3.13.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:1.3.13
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-1.3.18.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:1.3.18
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-1.3.19.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:1.3.19
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-1.3.20.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:1.3.20
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.0.1.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.0.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.11.1.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.11.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.14.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.14.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.16.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.16.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.17.1.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.17.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.18.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.19.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.19.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.19.2.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.19.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.5.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.5.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-2.8.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:2.8.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-dashboards-3.1.0.tar $IMAGE_REGISTRY/appscode-images/opensearch-dashboards:3.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-1.1.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:1.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-1.2.4.tar $IMAGE_REGISTRY/appscode-images/opensearch:1.2.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-1.3.13.tar $IMAGE_REGISTRY/appscode-images/opensearch:1.3.13
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-1.3.18.tar $IMAGE_REGISTRY/appscode-images/opensearch:1.3.18
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-1.3.19.tar $IMAGE_REGISTRY/appscode-images/opensearch:1.3.19
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-1.3.20.tar $IMAGE_REGISTRY/appscode-images/opensearch:1.3.20
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.0.1.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.0.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.11.1.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.11.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.14.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.14.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.16.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.16.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.17.1.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.17.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.18.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.19.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.19.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.19.2.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.19.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.5.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.5.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-2.8.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:2.8.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-opensearch-3.1.0.tar $IMAGE_REGISTRY/appscode-images/opensearch:3.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-percona-xtradb-cluster-5.7.44.tar $IMAGE_REGISTRY/appscode-images/percona-xtradb-cluster:5.7.44
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-percona-xtradb-cluster-8.0.40.tar $IMAGE_REGISTRY/appscode-images/percona-xtradb-cluster:8.0.40
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-percona-xtradb-cluster-8.4.3.tar $IMAGE_REGISTRY/appscode-images/percona-xtradb-cluster:8.4.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-pgpool2-4.4.5.tar $IMAGE_REGISTRY/appscode-images/pgpool2:4.4.5
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-pgpool2-4.4.8.tar $IMAGE_REGISTRY/appscode-images/pgpool2:4.4.8
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-pgpool2-4.5.0.tar $IMAGE_REGISTRY/appscode-images/pgpool2:4.5.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-pgpool2-4.5.3.tar $IMAGE_REGISTRY/appscode-images/pgpool2:4.5.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-pgpool2-4.6.0.tar $IMAGE_REGISTRY/appscode-images/pgpool2:4.6.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-pgpool2_exporter-v1.2.2.tar $IMAGE_REGISTRY/appscode-images/pgpool2_exporter:v1.2.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-documentdb-15-0.102.0-ferretdb-2.0.0.tar $IMAGE_REGISTRY/appscode-images/postgres-documentdb:15-0.102.0-ferretdb-2.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-documentdb-16-0.102.0-ferretdb-2.0.0.tar $IMAGE_REGISTRY/appscode-images/postgres-documentdb:16-0.102.0-ferretdb-2.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-documentdb-17-0.102.0-ferretdb-2.0.0.tar $IMAGE_REGISTRY/appscode-images/postgres-documentdb:17-0.102.0-ferretdb-2.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-10.23-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:10.23-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-10.23-bullseye.tar $IMAGE_REGISTRY/appscode-images/postgres:10.23-bullseye
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-11.22-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:11.22-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-11.22-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:11.22-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-12.17-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:12.17-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-12.17-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:12.17-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-12.22-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:12.22-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-12.22-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:12.22-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.13-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:13.13-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.13-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:13.13-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.18-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:13.18-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.18-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:13.18-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.20-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:13.20-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.20-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:13.20-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.21-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:13.21-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-13.21-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:13.21-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.10-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:14.10-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.10-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:14.10-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.13-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:14.13-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.13-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:14.13-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.15-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:14.15-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.15-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:14.15-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.17-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:14.17-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.17-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:14.17-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.18-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:14.18-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-14.18-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:14.18-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.10-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:15.10-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.10-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:15.10-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.12-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:15.12-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.12-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:15.12-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.13-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:15.13-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.13-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:15.13-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.5-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:15.5-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.5-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:15.5-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.8-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:15.8-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-15.8-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:15.8-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.1-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:16.1-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.1-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:16.1-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.4-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:16.4-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.4-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:16.4-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.6-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:16.6-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.6-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:16.6-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.8-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:16.8-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.8-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:16.8-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.9-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:16.9-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-16.9-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:16.9-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-17.2-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:17.2-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-17.2-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:17.2-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-17.4-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:17.4-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-17.4-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:17.4-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-17.5-alpine.tar $IMAGE_REGISTRY/appscode-images/postgres:17.5-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-postgres-17.5-bookworm.tar $IMAGE_REGISTRY/appscode-images/postgres:17.5-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-rabbitmq-3.12.12-management-alpine.tar $IMAGE_REGISTRY/appscode-images/rabbitmq:3.12.12-management-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-rabbitmq-3.13.2-management-alpine.tar $IMAGE_REGISTRY/appscode-images/rabbitmq:3.13.2-management-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-rabbitmq-4.0.4-management-alpine.tar $IMAGE_REGISTRY/appscode-images/rabbitmq:4.0.4-management-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-5.0.14-bullseye.tar $IMAGE_REGISTRY/appscode-images/redis:5.0.14-bullseye
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-6.0.20-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:6.0.20-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-6.2.14-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:6.2.14-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-6.2.16-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:6.2.16-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.0.14-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.0.14-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.0.15-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.0.15-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.2.3-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.2.3-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.2.4-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.2.4-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.2.6-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.2.6-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.4.0-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.4.0-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-redis-7.4.1-bookworm.tar $IMAGE_REGISTRY/appscode-images/redis:7.4.1-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-singlestore-node-alma-8.1.32-e3d3cde6da.tar $IMAGE_REGISTRY/appscode-images/singlestore-node:alma-8.1.32-e3d3cde6da
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-singlestore-node-alma-8.5.30-4f46ab16a5.tar $IMAGE_REGISTRY/appscode-images/singlestore-node:alma-8.5.30-4f46ab16a5
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-singlestore-node-alma-8.5.7-bf633c1a54.tar $IMAGE_REGISTRY/appscode-images/singlestore-node:alma-8.5.7-bf633c1a54
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-singlestore-node-alma-8.7.10-95e2357384.tar $IMAGE_REGISTRY/appscode-images/singlestore-node:alma-8.7.10-95e2357384
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-singlestore-node-alma-8.7.21-f0b8de04d5.tar $IMAGE_REGISTRY/appscode-images/singlestore-node:alma-8.7.21-f0b8de04d5
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-singlestore-node-alma-8.9.3-bfa36a984a.tar $IMAGE_REGISTRY/appscode-images/singlestore-node:alma-8.9.3-bfa36a984a
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-solr-8.11.4.tar $IMAGE_REGISTRY/appscode-images/solr:8.11.4
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-solr-9.4.1.tar $IMAGE_REGISTRY/appscode-images/solr:9.4.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-solr-9.6.1.tar $IMAGE_REGISTRY/appscode-images/solr:9.6.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-solr-9.7.0.tar $IMAGE_REGISTRY/appscode-images/solr:9.7.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-solr-9.8.0.tar $IMAGE_REGISTRY/appscode-images/solr:9.8.0
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-valkey-7.2.5.tar $IMAGE_REGISTRY/appscode-images/valkey:7.2.5
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-valkey-7.2.9.tar $IMAGE_REGISTRY/appscode-images/valkey:7.2.9
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-valkey-8.0.3.tar $IMAGE_REGISTRY/appscode-images/valkey:8.0.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-valkey-8.1.1.tar $IMAGE_REGISTRY/appscode-images/valkey:8.1.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-zookeeper-3.7.2.tar $IMAGE_REGISTRY/appscode-images/zookeeper:3.7.2
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-zookeeper-3.8.3.tar $IMAGE_REGISTRY/appscode-images/zookeeper:3.8.3
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-images-zookeeper-3.9.1.tar $IMAGE_REGISTRY/appscode-images/zookeeper:3.9.1
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-kubectl-nonroot-1.31.tar $IMAGE_REGISTRY/appscode/kubectl-nonroot:1.31
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-petset-v0.0.11.tar $IMAGE_REGISTRY/appscode/petset:v0.0.11
$CMD push --allow-nondistributable-artifacts --insecure images/appscode-sidekick-v0.0.11.tar $IMAGE_REGISTRY/appscode/sidekick:v0.0.11
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-cassandra-init-4.1.6-v2.tar $IMAGE_REGISTRY/kubedb/cassandra-init:4.1.6-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-cassandra-init-5.0.0-v2.tar $IMAGE_REGISTRY/kubedb/cassandra-init:5.0.0-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-cassandra-medusa-plugin-v0.4.0.tar $IMAGE_REGISTRY/kubedb/cassandra-medusa-plugin:v0.4.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-clickhouse-init-24.4.1-v3.tar $IMAGE_REGISTRY/kubedb/clickhouse-init:24.4.1-v3
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-dashboard-restic-plugin-v0.1.0.tar $IMAGE_REGISTRY/kubedb/dashboard-restic-plugin:v0.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-dashboard-restic-plugin-v0.15.0.tar $IMAGE_REGISTRY/kubedb/dashboard-restic-plugin:v0.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-druid-init-28.0.1.tar $IMAGE_REGISTRY/kubedb/druid-init:28.0.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-druid-init-30.0.1.tar $IMAGE_REGISTRY/kubedb/druid-init:30.0.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-druid-init-31.0.0.tar $IMAGE_REGISTRY/kubedb/druid-init:31.0.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-elasticsearch-restic-plugin-v0.20.0.tar $IMAGE_REGISTRY/kubedb/elasticsearch-restic-plugin:v0.20.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-hazelcast-init-5.5.2.tar $IMAGE_REGISTRY/kubedb/hazelcast-init:5.5.2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-ignite-init-2.17.0-v2.tar $IMAGE_REGISTRY/kubedb/ignite-init:2.17.0-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kafka-init-4.0-v1.tar $IMAGE_REGISTRY/kubedb/kafka-init:4.0-v1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-autoscaler-v0.42.0.tar $IMAGE_REGISTRY/kubedb/kubedb-autoscaler:v0.42.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-crd-manager-v0.12.0.tar $IMAGE_REGISTRY/kubedb/kubedb-crd-manager:v0.12.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-gitops-v0.5.0.tar $IMAGE_REGISTRY/kubedb/kubedb-gitops:v0.5.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-kibana-v0.33.0.tar $IMAGE_REGISTRY/kubedb/kubedb-kibana:v0.33.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-manifest-plugin-v0.20.0.tar $IMAGE_REGISTRY/kubedb/kubedb-manifest-plugin:v0.20.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-ops-manager-v0.44.0.tar $IMAGE_REGISTRY/kubedb/kubedb-ops-manager:v0.44.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-provisioner-v0.57.0.tar $IMAGE_REGISTRY/kubedb/kubedb-provisioner:v0.57.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-schema-manager-v0.33.0.tar $IMAGE_REGISTRY/kubedb/kubedb-schema-manager:v0.33.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-ui-server-v0.33.0.tar $IMAGE_REGISTRY/kubedb/kubedb-ui-server:v0.33.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-verifier-v0.1.0.tar $IMAGE_REGISTRY/kubedb/kubedb-verifier:v0.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-kubedb-webhook-server-v0.33.0.tar $IMAGE_REGISTRY/kubedb/kubedb-webhook-server:v0.33.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_10.10.7-jammy.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_10.10.7-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_10.11.6-jammy.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_10.11.6-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_10.4.32-focal.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_10.4.32-focal
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_10.5.23-focal.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_10.5.23-focal
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_10.6.16-focal.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_10.6.16-focal
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_11.0.4-jammy.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_11.0.4-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_11.1.3-jammy.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_11.1.3-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-archiver-v0.17.0_11.2.2-jammy.tar $IMAGE_REGISTRY/kubedb/mariadb-archiver:v0.17.0_11.2.2-jammy
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-coordinator-v0.37.0.tar $IMAGE_REGISTRY/kubedb/mariadb-coordinator:v0.37.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-csi-snapshotter-plugin-v0.17.0.tar $IMAGE_REGISTRY/kubedb/mariadb-csi-snapshotter-plugin:v0.17.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-init-0.7.0.tar $IMAGE_REGISTRY/kubedb/mariadb-init:0.7.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mariadb-restic-plugin-v0.15.0.tar $IMAGE_REGISTRY/kubedb/mariadb-restic-plugin:v0.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mongodb-csi-snapshotter-plugin-v0.18.0.tar $IMAGE_REGISTRY/kubedb/mongodb-csi-snapshotter-plugin:v0.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mongodb-init-4.2-v9.tar $IMAGE_REGISTRY/kubedb/mongodb-init:4.2-v9
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mongodb-init-6.0-v11.tar $IMAGE_REGISTRY/kubedb/mongodb-init:6.0-v11
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mongodb_exporter-v0.40.0.tar $IMAGE_REGISTRY/kubedb/mongodb_exporter:v0.40.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mssql-coordinator-v0.12.0.tar $IMAGE_REGISTRY/kubedb/mssql-coordinator:v0.12.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mssql-exporter-1.1.0.tar $IMAGE_REGISTRY/kubedb/mssql-exporter:1.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mssql-init-2022-ubuntu-22-v4.tar $IMAGE_REGISTRY/kubedb/mssql-init:2022-ubuntu-22-v4
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mssqlserver-archiver-v0.11.0.tar $IMAGE_REGISTRY/kubedb/mssqlserver-archiver:v0.11.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mssqlserver-walg-plugin-v0.11.0.tar $IMAGE_REGISTRY/kubedb/mssqlserver-walg-plugin:v0.11.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-archiver-v0.18.0_5.7.44.tar $IMAGE_REGISTRY/kubedb/mysql-archiver:v0.18.0_5.7.44
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-archiver-v0.18.0_8.0.35.tar $IMAGE_REGISTRY/kubedb/mysql-archiver:v0.18.0_8.0.35
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-archiver-v0.18.0_8.1.0.tar $IMAGE_REGISTRY/kubedb/mysql-archiver:v0.18.0_8.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-archiver-v0.18.0_8.2.0.tar $IMAGE_REGISTRY/kubedb/mysql-archiver:v0.18.0_8.2.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-archiver-v0.18.0_8.4.3.tar $IMAGE_REGISTRY/kubedb/mysql-archiver:v0.18.0_8.4.3
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-archiver-v0.18.0_9.1.0.tar $IMAGE_REGISTRY/kubedb/mysql-archiver:v0.18.0_9.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-coordinator-v0.35.0.tar $IMAGE_REGISTRY/kubedb/mysql-coordinator:v0.35.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-csi-snapshotter-plugin-v0.18.0.tar $IMAGE_REGISTRY/kubedb/mysql-csi-snapshotter-plugin:v0.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-init-5.7-v7.tar $IMAGE_REGISTRY/kubedb/mysql-init:5.7-v7
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-init-8.0.31-v6.tar $IMAGE_REGISTRY/kubedb/mysql-init:8.0.31-v6
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-init-8.4.2-v5.tar $IMAGE_REGISTRY/kubedb/mysql-init:8.4.2-v5
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-init-8.4.3-v5.tar $IMAGE_REGISTRY/kubedb/mysql-init:8.4.3-v5
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-init-9.0.1-v3.tar $IMAGE_REGISTRY/kubedb/mysql-init:9.0.1-v3
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-init-9.1.0-v3.tar $IMAGE_REGISTRY/kubedb/mysql-init:9.1.0-v3
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysql-router-init-v0.35.0.tar $IMAGE_REGISTRY/kubedb/mysql-router-init:v0.35.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-mysqld-exporter-v0.13.1.tar $IMAGE_REGISTRY/kubedb/mysqld-exporter:v0.13.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-oracle-coordinator-v0.3.0.tar $IMAGE_REGISTRY/kubedb/oracle-coordinator:v0.3.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-oracle-ee-21.3.0.tar $IMAGE_REGISTRY/kubedb/oracle-ee:21.3.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-oracle-init-v0.1.0.tar $IMAGE_REGISTRY/kubedb/oracle-init:v0.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-percona-xtradb-coordinator-v0.30.0.tar $IMAGE_REGISTRY/kubedb/percona-xtradb-coordinator:v0.30.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-percona-xtradb-init-0.2.3.tar $IMAGE_REGISTRY/kubedb/percona-xtradb-init:0.2.3
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-pg-coordinator-v0.41.0.tar $IMAGE_REGISTRY/kubedb/pg-coordinator:v0.41.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-pgbouncer-1.17.0.tar $IMAGE_REGISTRY/kubedb/pgbouncer:1.17.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-pgbouncer-1.18.0.tar $IMAGE_REGISTRY/kubedb/pgbouncer:1.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-pgbouncer-1.23.1.tar $IMAGE_REGISTRY/kubedb/pgbouncer:1.23.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-pgbouncer-1.24.0.tar $IMAGE_REGISTRY/kubedb/pgbouncer:1.24.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-pgbouncer_exporter-v0.1.1.tar $IMAGE_REGISTRY/kubedb/pgbouncer_exporter:v0.1.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_11.22-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_11.22-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_11.22-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_11.22-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_12.17-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_12.17-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_12.17-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_12.17-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_13.13-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_13.13-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_13.13-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_13.13-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_14.10-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_14.10-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_14.10-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_14.10-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_15.5-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_15.5-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_15.5-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_15.5-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_16.1-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_16.1-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_16.1-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_16.1-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_17.2-alpine.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_17.2-alpine
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-archiver-v0.18.0_17.2-bookworm.tar $IMAGE_REGISTRY/kubedb/postgres-archiver:v0.18.0_17.2-bookworm
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-csi-snapshotter-plugin-v0.18.0.tar $IMAGE_REGISTRY/kubedb/postgres-csi-snapshotter-plugin:v0.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-init-0.17.2.tar $IMAGE_REGISTRY/kubedb/postgres-init:0.17.2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-postgres-restic-plugin-v0.20.0_16.1.tar $IMAGE_REGISTRY/kubedb/postgres-restic-plugin:v0.20.0_16.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-provider-aws-v0.18.0.tar $IMAGE_REGISTRY/kubedb/provider-aws:v0.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-provider-azure-v0.18.0.tar $IMAGE_REGISTRY/kubedb/provider-azure:v0.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-provider-gcp-v0.18.0.tar $IMAGE_REGISTRY/kubedb/provider-gcp:v0.18.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-exporter-v1.1.0.tar $IMAGE_REGISTRY/kubedb/proxysql-exporter:v1.1.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-2.3.2-centos-v2.tar $IMAGE_REGISTRY/kubedb/proxysql:2.3.2-centos-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-2.3.2-debian-v2.tar $IMAGE_REGISTRY/kubedb/proxysql:2.3.2-debian-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-2.4.4-centos.tar $IMAGE_REGISTRY/kubedb/proxysql:2.4.4-centos
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-2.4.4-debian.tar $IMAGE_REGISTRY/kubedb/proxysql:2.4.4-debian
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-2.6.3-debian.tar $IMAGE_REGISTRY/kubedb/proxysql:2.6.3-debian
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-2.7.3-debian.tar $IMAGE_REGISTRY/kubedb/proxysql:2.7.3-debian
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-proxysql-3.0.1-debian.tar $IMAGE_REGISTRY/kubedb/proxysql:3.0.1-debian
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-rabbitmq-init-3.12.12.tar $IMAGE_REGISTRY/kubedb/rabbitmq-init:3.12.12
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-rabbitmq-init-3.13.2.tar $IMAGE_REGISTRY/kubedb/rabbitmq-init:3.13.2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-rabbitmq-init-4.0.4.tar $IMAGE_REGISTRY/kubedb/rabbitmq-init:4.0.4
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-redis-coordinator-v0.36.0.tar $IMAGE_REGISTRY/kubedb/redis-coordinator:v0.36.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-redis-init-0.12.0.tar $IMAGE_REGISTRY/kubedb/redis-init:0.12.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-redis-restic-plugin-v0.20.0.tar $IMAGE_REGISTRY/kubedb/redis-restic-plugin:v0.20.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-redis-4.0.11.tar $IMAGE_REGISTRY/kubedb/redis:4.0.11
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-redis_exporter-1.66.0.tar $IMAGE_REGISTRY/kubedb/redis_exporter:1.66.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-replication-mode-detector-v0.44.0.tar $IMAGE_REGISTRY/kubedb/replication-mode-detector:v0.44.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-singlestore-coordinator-v0.12.0.tar $IMAGE_REGISTRY/kubedb/singlestore-coordinator:v0.12.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-singlestore-init-8.1-v2.tar $IMAGE_REGISTRY/kubedb/singlestore-init:8.1-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-singlestore-init-8.5-v2.tar $IMAGE_REGISTRY/kubedb/singlestore-init:8.5-v2
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-singlestore-init-8.7.10-v1.tar $IMAGE_REGISTRY/kubedb/singlestore-init:8.7.10-v1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-solr-init-8.11.4.tar $IMAGE_REGISTRY/kubedb/solr-init:8.11.4
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-solr-init-9.4.1.tar $IMAGE_REGISTRY/kubedb/solr-init:9.4.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-solr-init-9.6.1.tar $IMAGE_REGISTRY/kubedb/solr-init:9.6.1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-solr-init-9.7.0.tar $IMAGE_REGISTRY/kubedb/solr-init:9.7.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-solr-init-9.8.0.tar $IMAGE_REGISTRY/kubedb/solr-init:9.8.0
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-wal-g-v2024.12.18_mongo.tar $IMAGE_REGISTRY/kubedb/wal-g:v2024.12.18_mongo
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-zookeeper-init-3.7-v1.tar $IMAGE_REGISTRY/kubedb/zookeeper-init:3.7-v1
$CMD push --allow-nondistributable-artifacts --insecure images/kubedb-zookeeper-restic-plugin-v0.13.0.tar $IMAGE_REGISTRY/kubedb/zookeeper-restic-plugin:v0.13.0
$CMD push --allow-nondistributable-artifacts --insecure images/hazelcast-hazelcast-enterprise-5.5.2.tar $IMAGE_REGISTRY/hazelcast/hazelcast-enterprise:5.5.2
$CMD push --allow-nondistributable-artifacts --insecure images/hazelcast-hazelcast-enterprise-5.5.6.tar $IMAGE_REGISTRY/hazelcast/hazelcast-enterprise:5.5.6
$CMD push --allow-nondistributable-artifacts --insecure images/mariadb-maxscale-24.02.4.tar $IMAGE_REGISTRY/mariadb/maxscale:24.02.4
$CMD push --allow-nondistributable-artifacts --insecure images/mssql-server-2022-CU12-ubuntu-22.04.tar $IMAGE_REGISTRY/mssql/server:2022-CU12-ubuntu-22.04
$CMD push --allow-nondistributable-artifacts --insecure images/mssql-server-2022-CU14-ubuntu-22.04.tar $IMAGE_REGISTRY/mssql/server:2022-CU14-ubuntu-22.04
$CMD push --allow-nondistributable-artifacts --insecure images/mssql-server-2022-CU16-ubuntu-22.04.tar $IMAGE_REGISTRY/mssql/server:2022-CU16-ubuntu-22.04
$CMD push --allow-nondistributable-artifacts --insecure images/mssql-server-2022-CU19-ubuntu-22.04.tar $IMAGE_REGISTRY/mssql/server:2022-CU19-ubuntu-22.04
$CMD push --allow-nondistributable-artifacts --insecure images/mysql-mysql-router-8.0.31.tar $IMAGE_REGISTRY/mysql/mysql-router:8.0.31
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-4.2.24.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:4.2.24
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-4.4.26.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:4.4.26
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-5.0.23.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:5.0.23
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-5.0.29.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:5.0.29
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-6.0.12.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:6.0.12
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-6.0.24.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:6.0.24
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-7.0.18.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:7.0.18
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-7.0.4.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:7.0.4
$CMD push --allow-nondistributable-artifacts --insecure images/percona-percona-server-mongodb-8.0.8.tar $IMAGE_REGISTRY/percona/percona-server-mongodb:8.0.8
$CMD push --allow-nondistributable-artifacts --insecure images/postgis-postgis-11-3.3.tar $IMAGE_REGISTRY/postgis/postgis:11-3.3
$CMD push --allow-nondistributable-artifacts --insecure images/postgis-postgis-12-3.4.tar $IMAGE_REGISTRY/postgis/postgis:12-3.4
$CMD push --allow-nondistributable-artifacts --insecure images/postgis-postgis-13-3.4.tar $IMAGE_REGISTRY/postgis/postgis:13-3.4
$CMD push --allow-nondistributable-artifacts --insecure images/postgis-postgis-14-3.4.tar $IMAGE_REGISTRY/postgis/postgis:14-3.4
$CMD push --allow-nondistributable-artifacts --insecure images/postgis-postgis-15-3.4.tar $IMAGE_REGISTRY/postgis/postgis:15-3.4
$CMD push --allow-nondistributable-artifacts --insecure images/postgis-postgis-16-3.4.tar $IMAGE_REGISTRY/postgis/postgis:16-3.4
$CMD push --allow-nondistributable-artifacts --insecure images/prom-memcached-exporter-v0.14.2.tar $IMAGE_REGISTRY/prom/memcached-exporter:v0.14.2
$CMD push --allow-nondistributable-artifacts --insecure images/prom-mysqld-exporter-v0.13.0.tar $IMAGE_REGISTRY/prom/mysqld-exporter:v0.13.0
$CMD push --allow-nondistributable-artifacts --insecure images/prometheuscommunity-elasticsearch-exporter-v1.7.0.tar $IMAGE_REGISTRY/prometheuscommunity/elasticsearch-exporter:v1.7.0
$CMD push --allow-nondistributable-artifacts --insecure images/prometheuscommunity-postgres-exporter-v0.15.0.tar $IMAGE_REGISTRY/prometheuscommunity/postgres-exporter:v0.15.0
$CMD push --allow-nondistributable-artifacts --insecure images/git-sync-git-sync-v4.2.1.tar $IMAGE_REGISTRY/git-sync/git-sync:v4.2.1
$CMD push --allow-nondistributable-artifacts --insecure images/singlestore-cluster-in-a-box-alma-8.1.32-e3d3cde6da-4.0.16-1.17.6.tar $IMAGE_REGISTRY/singlestore/cluster-in-a-box:alma-8.1.32-e3d3cde6da-4.0.16-1.17.6
$CMD push --allow-nondistributable-artifacts --insecure images/singlestore-cluster-in-a-box-alma-8.5.22-fe61f40cd1-4.1.0-1.17.11.tar $IMAGE_REGISTRY/singlestore/cluster-in-a-box:alma-8.5.22-fe61f40cd1-4.1.0-1.17.11
$CMD push --allow-nondistributable-artifacts --insecure images/singlestore-cluster-in-a-box-alma-8.5.7-bf633c1a54-4.0.17-1.17.8.tar $IMAGE_REGISTRY/singlestore/cluster-in-a-box:alma-8.5.7-bf633c1a54-4.0.17-1.17.8
$CMD push --allow-nondistributable-artifacts --insecure images/singlestore-cluster-in-a-box-alma-8.7.10-95e2357384-4.1.0-1.17.14.tar $IMAGE_REGISTRY/singlestore/cluster-in-a-box:alma-8.7.10-95e2357384-4.1.0-1.17.14
$CMD push --allow-nondistributable-artifacts --insecure images/tianon-toybox-0.8.11.tar $IMAGE_REGISTRY/tianon/toybox:0.8.11
$CMD push --allow-nondistributable-artifacts --insecure images/timescale-timescaledb-2.14.2-pg13-oss.tar $IMAGE_REGISTRY/timescale/timescaledb:2.14.2-pg13-oss
$CMD push --allow-nondistributable-artifacts --insecure images/timescale-timescaledb-2.14.2-pg14-oss.tar $IMAGE_REGISTRY/timescale/timescaledb:2.14.2-pg14-oss
$CMD push --allow-nondistributable-artifacts --insecure images/timescale-timescaledb-2.14.2-pg15-oss.tar $IMAGE_REGISTRY/timescale/timescaledb:2.14.2-pg15-oss
$CMD push --allow-nondistributable-artifacts --insecure images/timescale-timescaledb-2.14.2-pg16-oss.tar $IMAGE_REGISTRY/timescale/timescaledb:2.14.2-pg16-oss
