apiVersion: catalog.kubedb.com/v1alpha1
kind: DocumentDBVersion
metadata:
  name: pg17-0.109.0
spec:
  coordinator:
    image: ghcr.io/kubedb/documentdb-coordinator:v0.2.0
  db:
    image: ghcr.io/documentdb/documentdb/documentdb-local:pg17-0.109.0
  initContainer:
    image: ghcr.io/kubedb/documentdb-init:0.1.0
  postgresVersion: "17"
  securityContext:
    runAsUser: 1000
  version: 0.109.0
