apiVersion: catalog.kubedb.com/v1alpha1
kind: DocumentDBVersion
metadata:
  name: pg17-0.109.0
spec:
  db:
    image: ghcr.io/documentdb/documentdb/documentdb-local:pg17-0.109.0
  postgresVersion: "17"
  securityContext:
    runAsUser: 1000
  version: 0.109.0
