apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: installer
    app.kubernetes.io/managed-by: kustomize
  name: kubedb-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedb-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
