apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - petsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - placementpolicies
  verbs:
  - '*'
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - archiver.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - elasticsearchautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - etcdautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - kafkaautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - mariadbautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - memcachedautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - mongodbautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - mssqlserverautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - mysqlautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - perconaxtradbautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - pgbouncerautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - postgresautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - proxysqlautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - rabbitmqautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kubedb.com
  resources:
  - redisautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - cacerts.csi.cert-manager.io
  resources:
  - caproviderclasses
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - catalog.kubedb.com
  resources:
  - elasticsearchversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - mariadbversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - mongodbversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - mysqlversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - postgresversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubedb.com
  resources:
  - redisversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - features.ace.info
  resources:
  - clusterclaims
  verbs:
  - get
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubestash.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.kubestash.com
  resources:
  - backupconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubestash.com
  resources:
  - backupsessions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubestash.com
  resources:
  - restoresessions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticsearch.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - elasticsearch.kubedb.com
  resources:
  - elasticsearchdashboards/finalizers
  verbs:
  - update
- apiGroups:
  - elasticsearch.kubedb.com
  resources:
  - elasticsearchdashboards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticsearch.kubedb.com
  resources:
  - elasticsearchdashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - mariadbroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - mongodbroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - mysqlroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - postgresroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - redisroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - secretaccessrequests/status
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - engine.kubevault.com
  resources:
  - secretaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - engine.kubevault.com
  resources:
  - secretengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - installer.kubedb.com
  resources:
  - kubedbs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - installer.kubedb.com
  resources:
  - kubedbs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - installer.kubedb.com
  resources:
  - kubedbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubedb.com
  resources:
  - elasticsearches/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - elasticsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedb.com
  resources:
  - etcds/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - mariadbs/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - mariadbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedb.com
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - mongodbs/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - mongodbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedb.com
  resources:
  - mysqls/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - mysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedb.com
  resources:
  - perconaxtradbs/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - pgbouncers/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - postgreses/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - postgreses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedb.com
  resources:
  - proxysqls/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - redises/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - redises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedb.com
  resources:
  - redissentinels/finalizers
  verbs:
  - update
- apiGroups:
  - kubedb.com
  resources:
  - zookeepers/finalizers
  verbs:
  - update
- apiGroups:
  - kubestash.appscode.com
  resources:
  - restorebatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubestash.appscode.com
  resources:
  - restoresessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevault.com
  resources:
  - vaultservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - migrator.kubedb.com
  resources:
  - migratoraddons
  verbs:
  - '*'
- apiGroups:
  - migrator.kubedb.com
  resources:
  - migrators/finalizers
  verbs:
  - '*'
- apiGroups:
  - migrator.kubedb.com
  resources:
  - migrators/status
  verbs:
  - '*'
- apiGroups:
  - migrator.kubedb.com
  resources:
  - migrators
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - networking.kubeslice.io
  resources:
  - serviceimports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.k8s.appscode.com
  resources:
  - nodetopologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.k8s.appscode.com
  resources:
  - shardconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ops.kubedb.com
  resources:
  - elasticsearchopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - etcdopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - kafkaopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - mariadbopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - memcachedopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - mongodbopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - mysqlopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - perconaxtradbopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - pgbounceropsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - postgresopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - proxysqlopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ops.kubedb.com
  resources:
  - redisopsrequests/finalizers
  verbs:
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
- apiGroups:
  - postgres.kubedb.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - postgres.kubedb.com
  resources:
  - publishers/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.kubedb.com
  resources:
  - subscribers/finalizers
  verbs:
  - update
- apiGroups:
  - proxyserver.licenses.appscode.com
  resources:
  - licenserequests
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - '*'
- apiGroups:
  - scanner.appscode.com
  resources:
  - imagescanreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scanner.appscode.com
  resources:
  - imagescanrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - schema.kubedb.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - schema.kubedb.com
  resources:
  - mariadbdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - mariadbdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schema.kubedb.com
  resources:
  - mongodbdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - mongodbdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - mongodbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schema.kubedb.com
  resources:
  - mysqldatabases/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - mysqldatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - mysqldatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schema.kubedb.com
  resources:
  - postgresdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - postgresdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - postgresdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schema.kubedb.com
  resources:
  - redisdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - redisdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - schema.kubedb.com
  resources:
  - redisdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stash.appscode.com
  resources:
  - backupconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stash.appscode.com
  resources:
  - backupsessions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stash.appscode.com
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - stash.appscode.com
  resources:
  - restorebatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stash.appscode.com
  resources:
  - restoresessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.kubestash.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - supervisor.appscode.com
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.kubedb.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virtual-secrets.dev
  resources:
  - secrets/mount
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtual-secrets.dev
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resourceNames:
  - ace-info
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- nonResourceURLs:
  - /appscode/license
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
