# This rule is not used by the project kubedb-installer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to installer.kubedb.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubedb-installer
    app.kubernetes.io/managed-by: kustomize
  name: kubedb-viewer-role
rules:
- apiGroups:
  - installer.kubedb.com
  resources:
  - kubedbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - installer.kubedb.com
  resources:
  - kubedbs/status
  verbs:
  - get
