---
# Source: kubedb/charts/petset/templates/webhook-server/webhook_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kubedb-petset-webhook
  namespace: kubedb
  labels:
    helm.sh/chart: petset-v2024.9.30
    app.kubernetes.io/name: petset
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/component: webhook-server
    app.kubernetes.io/name: petset
    app.kubernetes.io/instance: kubedb
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
