apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: clickhouse-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --wait-timeout=${waitTimeout:=300}
  image: ghcr.io/kubedb/clickhouse-backup-plugin:v0.2.0-rc.0
