apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: clickhouse-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --wait-timeout=${waitTimeout:=300}
  - --snapshot=${snapshot:=}
  image: ghcr.io/kubedb/clickhouse-backup-plugin:v0.1.0
