apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: clickhouse-incremental-restore
spec:
  args:
    - pitr-restore
    - --namespace=${namespace:=default}
    - --restoresession=${restoreSession:=}
    - --wait-timeout=${waitTimeout:=300}
    - --snapshot=${snapshot:=}
    - --pitr-time=${pitrTime:=}
  image: ghcr.io/kubedb/clickhouse-backup-plugin:v0.3.0
