{{- if and (eq "prometheus.io/operator" ( include "monitoring.agent" . )) .Values.monitoring.serviceMonitor.bearerTokenSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-metrics-token" (include "kubedb-ui-server.fullname" .)) .Values.monitoring.serviceMonitor.bearerTokenSecret.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubedb-ui-server.serviceAccountName" . }}
  labels:
    {{- include "kubedb-ui-server.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
