{{- $tokenSecretName := printf "%s-metrics-token" (include "kubedb-ui-server.fullname" .) -}}
{{- if and (eq "prometheus.io/operator" ( include "monitoring.agent" . )) (not (lookup "v1" "Secret" .Release.Namespace $tokenSecretName)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $tokenSecretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubedb-ui-server.serviceAccountName" . }}
  labels:
    {{- include "kubedb-ui-server.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
