apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: solr-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  image: ghcr.io/kubedb/solr-backup-plugin:v0.1.0
