apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: installer.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Kubernetes-native Database-as-a-Service (DBaaS) Anywhere with Any Storage
  displayName: KubeDB by AppsCode
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubedb
  - dbaas
  - openshift
  - kubernetes
  links:
  - name: Installer
    url: https://installer.domain
  maintainers:
  - email: support@appscode.com
    name: appscode
  maturity: alpha
  provider:
    name: AppsCode
    url: https://kubedb.com
  version: 0.0.0
