apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Auto Pilot
    categories: Database
    containerImage: ghcr.io/kubedb/kubedb-installer:v2026.2.26
    description: Database-as-a-Service (DBaaS) Anywhere with Any Storage
    repository: github.com/kubedb/installer
    support: AppsCode Inc.
  name: kubedb-installer.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KubeDB Operator
      displayName: Kubedbs
      kind: Kubedb
      name: kubedbs.installer.kubedb.com
      version: v1
  description: Database-as-a-Service (DBaaS) Anywhere with Any Storage
  displayName: KubeDB by AppsCode
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAMAAAADABAMAAACg8nE0AAAAKlBMVEVHcExJSaNJSaNJSaNJSaNycun///9bW7tQUK1oaNh9fb7i4vG0tNlHcExurK8FAAAADnRSTlMAxUKH////////////AOnOVCwAAAa2SURBVHja1VzLbts4FE2cH2iS+QBn8gPuIIvZuhYgtXshzQ9o4yw1qB1k1TEQ2GsbjvcFGmC8zqKTdQo081GjWH6Q98VLiWphboq21j0+OoeXNHnJgwOf1rrotg8abK23UdRrEKH1W1S05jgcreIXCH80E/98Hb8phLNo17onjchrtpOG40fRaTu8fZpDOCfih7Tr+SgiW7cT5vWcRVwLYlcgbzIKjNC6sOMPr3Lzr7XtemTLG8/S9GoQ0EzAPndF/KAI5xERHyFUz9+g935axy/aPESHgNlhmBptXt9MIDskVvwACOdy/DS9HNXKrjD+LEXN6hCFmSoPLmv7EwiV7QrlvSPjV7erNn5Vu8LBZZwKrYKZnPapiQAGF1d8aFfndAO8fnd8ZNcTH3mTWapoeruCwUWyTyUEMLjQ8RcLCuFeY1c4NxkT8RefRrQsc/d0A84dhqwnh1Xs2tLYZy69OxlBFX/gUGfETzdgdiCz88CVXmH+brPxY3f2Jymydj1023MBp6cahG3+PnTGnxPTX+pzV3T+PtTZE3JQmOkzAqCYg6/lSFUWQg8CkPEH7PSdFMLM3xhg5hOffqGm33pYg6FsT7fU1gMEQDKWplduBPuBnsumtH1An1vwfus5Ohq0T/n7KXl64KSGX4gG2DyB5I2XX1Z/PPa/0gjIzwxA+QSK/+ElWwNk/R8jgjT2GwdQmGmG7DN5zkqA5DHLMoxA+dkESOz/v4Py3r6G3TAo2hOU2no+Lh//2wCIxR6VLFdRdwwKhAfJuyV812QA5wbWF/pnFdNkkGVAavuFYYCYs30prwGwZlAg/KA//tpXc6wB27GiySa+zQBLbZiWZlB4k3jiZhfQZoCl3nWKKaEBkzyXRjzIAEu9ycccA4SQLI1omEGWXX8l00zOMQATzfglQwAWA1vqXRrjGVhST+z4FIPMyBtGqp/yDIp2j+XlGRTtW4nw3gghMkg/YnkFBpt/dwAkCIALFFcDiNEr4gKpGEwVDGJfBmPEIBE1SOowyH8Og6g5Bj9Jg6gtuSiABsmvYhBMAxOgEQbddsP9oHEGDbpo+msZ7L8GH/deg/v90aCz9xp09r4fdJrORZ2916Cz9/2gs78uqqXBc2Ma9MtAN89qDd54Mdj+2oO/DQMx6H/nft3yGvgwuH7AyzshXfT0hVpACqfBt1xYI+EZvFFq0KfWbQyp62pgyBuRCxk1GVw/sCt5QTQQVv+S28dKDCwX2fLefKekrqOBLe/tI9R7JXV1DeyFxdL8AOF1SbKyBvbS6Gb1FKwExsvKDGx5d66E6/vLihr8lzP9Kvv3gVuQBT/ERRdFIy4zMF3PVwO8+E6uBEoMonfimh2bnZllZUKDEx2DjX3shpaVxyKAwACOX9yyMqHBOw2DCRMfmYlg8Fl0EbM6y5rpvSgyx+BWiA/MVMlFxCyLmirV0ODDixTfGov0DC41HsI++kutgb3RYu9R8D3BKmaQGdg2Ivsx0ZetjWJZA7RNTVkJZiO7GsPBAO0VTZ7lLoCqPWQNiK1V2J3hVAZuvbsY4M1h20xPjvguDajtbdNMcCsW1+Ll5n4vzYBAeKTtQ5VX5AoGuGSmNFNfEV/HANv11UzQPnSt3BQBJJoKt8JM0D50qaiWAUaIXfZhARKuSm/uVXnizUDYJ+cq4rw0EBGkUksfBvQ+uaOUM/dhQBcBJYs0DcWA2omP5VLOqR8DjOAqFfVlAEc5Zylq7svANtPY+eE1QNeDwQ5BUwk8rcBgW8CliF+NQZqO1KXGGCBRfy8NwKZrGgAqBC2DrR+6VgnWMBSDnd9sALe7dQyMBF8CHMkVnr4AA1RF1lL3UMUrsnNKOas4uNCWu7sZgJzVwSeGRDM5AS7JWkf7VIBznBIAwNhnlKif6UZaBwNYq9nmSutZqUUAOP8AxwRUCNIrgkMSOoZg1Y8zA6LAAMY/cRzQoId0HgBMC+jjLK23qjlz4i5dZ4/LnDkQOAbQnm3dMZ+xFgDEF49dyWaiX5HLPoKZIALFQGEfgPCn49evDQDia85bCWbCDBa5d3zJTIiB3j7Cic8hz0DKbh6n0sYzhsHcyz52+500k8UAVjl7npy0jnbdzTADWFrrffbTNtMMMqhgT/F4nVHsvAKA2bPa+Vs0GdgyqG4fwUzDHQOf7OZlpjXAvJZ9eDMl5ZkBcJAgqnnSHd+SENW3j/YigCjQbQMCQqALROjLGKKANz4c0QinB8EadWFFFPTmEGym0DeTQIRAl1WwZmrkdhjDTKdNxDcQGoq/NVNDV9uUUh8fH/vF/x8kM/J80KqROwAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - kubedb
  - dbaas
  - openshift
  - kubernetes
  links:
  - name: KubeDB Docs
    url: https://kubedb.com
  maintainers:
  - email: support@appscode.com
    name: AppsCode
  maturity: alpha
  minKubeVersion: 1.28.0-0
  provider:
    name: AppsCode Inc.
    url: https://appscode.com
  version: 0.0.0
