apiVersion: v2
description: KubeDB Autoscaler by AppsCode - Autoscale KubeDB operated Databases
name: kubedb-autoscaler
version: v0.51.0
appVersion: v0.51.0
kubeVersion: '>=1.26.0-0'
annotations:
  charts.openshift.io/name: kubedb-autoscaler
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb
dependencies:
- name: storage-metrics-server
  repository: oci://ghcr.io/appscode-charts
  condition: storage-metrics-server.enabled
  version: v0.1.0
maintainers:
- name: appscode
  email: support@appscode.com
