apiVersion: installer.kubedb.com/v1
kind: Kubedb
metadata:
  name: kubedb-sample
spec:
  global:
    license: ""
    licenseSecretName: ""
    registry: ""
    registryFQDN: ""
    insecureRegistries: []
    imagePullSecrets: []
    featureGates:
      Cassandra: false
      ClickHouse: false
      DB2: false
      Druid: false
      Elasticsearch: true
      FerretDB: false
      HanaDB: false
      Hazelcast: false
      Ignite: false
      Kafka: true
      MariaDB: true
      Memcached: false
      Milvus: false
      MongoDB: true
      MSSQLServer: false
      MySQL: true
      Neo4j: false
      Oracle: false
      PerconaXtraDB: false
      PgBouncer: false
      Pgpool: false
      Postgres: true
      ProxySQL: false
      Qdrant: false
      RabbitMQ: false
      Redis: true
      Singlestore: false
      Solr: false
      Weaviate: false
      ZooKeeper: false
    networkPolicy:
      enabled: false
