---
# Source: kubedb/charts/kubedb-catalog/templates/rabbitmq/rabbitmq-3.12.12.yaml
apiVersion: catalog.kubedb.com/v1alpha1
kind: RabbitMQVersion
metadata:
  name: '3.12.12'
  labels:
    helm.sh/chart: kubedb-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  db:
    image: 'ghcr.io/appscode-images/rabbitmq:3.12.12-management-alpine'
  initContainer:
    image: 'ghcr.io/kubedb/rabbitmq-init:3.12.12'
  securityContext:
    runAsUser: 999
  version: 3.12.12
