apiVersion: catalog.kubedb.com/v1alpha1
kind: Neo4jVersion
metadata:
  name: 2026.05.0
spec:
  db:
    image: docker.io/library/neo4j:2026.05.0-enterprise
  gitSyncer:
    image: registry.k8s.io/git-sync/git-sync:v4.4.2
  securityContext:
    runAsUser: 7474
  version: 2026.05.0-enterprise
