apiVersion: v1
kind: Secret
metadata:
  name: hz
stringData:
  hazelcast.yaml: |-
    hazelcast:
      jet:
        enabled: true
        instance:
            backup-count: 2
            scale-up-delay-millis: 15000
      persistence:
        validation-timeout-seconds: 1500
#      advanced-network:
#        enabled: true
#        join:
#            kubernetes:
#                enabled: true
#                service-name: hz
#                service-namespace: default
#                service-per-pod-label-name: hazelcast.com/service-per-pod
#                service-per-pod-label-value: "true"
#                service-port: 5702
#        member-server-socket-endpoint-config:
#            port:
#                port: 5701
#                port-count: 1
#        client-server-socket-endpoint-config:
#            port:
#                port: 9090
#                port-count: 1
#        rest-server-socket-endpoint-config:
#            port:
#                port: 8081
#                port-count: 1
#            endpoint-groups:
#                HEALTH_CHECK:
#                    enabled: true
#                CLUSTER_WRITE:
#                    enabled: true
#                PERSISTENCE:
#                    enabled: true
#        wan-server-socket-endpoint-config:
#            default:
#                port:
#                    port: 5710
#                    port-count: 1
