apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: weaviate-restore
spec:
  args:
    - restore
    - --namespace=${namespace:=default}
    - --restoresession=${restoreSession:=}
    - --snapshot=${snapshot:=}
    - --wait-timeout=${waitTimeout:=300}
  #    - --classes=${classes:=}
  #    - --no-recovery=${noRecovery:=false}
  image: tutul108/weaviate-backup:weaviate_backup_linux_amd64027