apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: qdrant-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --wait-timeout=${waitTimeout:=300}
  - --collections=${collections:=}
  image: ghcr.io/kubedb/qdrant-restore-plugin:v0.1.0
