apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: qdrant-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  image: ghcr.io/kubedb/qdrant-restic-plugin:v0.2.0
