---
# Source: kubedb/charts/kubedb-kubestash-catalog/templates/postgres/postgres-restore.yaml
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'postgres-restore'
  labels:
    helm.sh/chart: kubedb-kubestash-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --pg-args=${args:=}
  - --user=${user:=}
  availableVersions:
  - "12.17"
  - "14.10"
  - "16.1"
  - "17.2"
  image: 'ghcr.io/kubedb/postgres-restic-plugin:v0.14.0_${DB_VERSION}'
