apiVersion: catalog.kubedb.com/v1alpha1
kind: RabbitMQVersion
metadata:
  name: 4.2.6-dhi
spec:
  db:
    image: dhi.io/rabbitmq:4.2.6
  initContainer:
    image: ghcr.io/kubedb/rabbitmq-init:v2026.1.19
  securityContext:
    runAsUser: 65532
  version: 4.2.6