---
# Source: kubedb/charts/kubedb-kubestash-catalog/templates/kubedbmanifest/kubedbmanifest-backup.yaml
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'kubedbmanifest-backup'
  labels:
    helm.sh/chart: kubedb-kubestash-catalog-v2025.1.9
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v2025.1.9"
    app.kubernetes.io/managed-by: Helm
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  image: 'ghcr.io/kubedb/kubedb-manifest-plugin:v0.14.0'
