---
# Source: kubedb/charts/kubedb-crd-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedb-kubedb-crd-manager
  labels:
    helm.sh/chart: kubedb-crd-manager-v0.6.0
    app.kubernetes.io/name: kubedb-crd-manager
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
automountServiceAccountToken:
