{{ $featureGates := .Values.featureGates }}
{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and $featureGates.DocumentDB (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: 'documentdb-addon'
  labels:
    {{- include "kubedb-kubestash-catalog.labels" . | nindent 4 }}
spec:
  backupTasks:
  - driver: Restic
    executor: Job
    function: documentdb-backup
    name: logical-backup
    parameters:
    - name: args
      required: false
      usage: Arguments to be passed to the dump command.
    - default: pg_dumpall
      name: backupCmd
      required: false
      usage: Backup command to take a database dump (can only be pg_dumpall or pg_dump)
    - name: user
      required: false
      usage: Specifies database user (not applicable for basic authentication)
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  - driver: Restic
    executor: Job
    function: documentdb-physical-backup
    name: physical-backup
    parameters:
    - name: args
      required: false
      usage: Arguments to be passed to the backup command.
    - default: pg_basebackup
      name: backupCmd
      required: false
      usage: Backup command to take a physical database backup (pg_basebackup)
    - name: user
      required: false
      usage: Specifies database user (not applicable for basic authentication)
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  - driver: Restic
    executor: Job
    function: kubedbmanifest-backup
    name: manifest-backup
    parameters:
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  restoreTasks:
  - driver: Restic
    executor: Job
    function: documentdb-restore
    name: logical-backup-restore
    parameters:
    - name: args
      required: false
      usage: Arguments to be passed to the restore command.
    - name: user
      required: false
      usage: Specifies database user (not applicable for basic authentication)
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  - driver: Restic
    executor: Job
    function: documentdb-physical-backup-restore
    name: physical-backup-restore
    parameters:
    - name: args
      required: false
      usage: Arguments to be passed to the restore command.
    - name: user
      required: false
      usage: Specifies database user (not applicable for basic authentication)
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    - default: tar
      name: restoreCmd
      required: false
      usage: Restore command to use on dumped restic tar file
    - default: /data
      name: restorePath
      required: false
      usage: Path within the mounted volume that becomes PGDATA (/var/pv/data)
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-data
      name: kubestash-data-volume
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-data-volume
      source:
        persistentVolumeClaim:
          claimName: ${PVC_NAME}
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  - driver: Restic
    executor: Job
    function: kubedbmanifest-restore
    name: manifest-restore
    parameters:
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
{{ end }}
