{{ $featureGates := .Values.featureGates }}
{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and $featureGates.Etcd (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'etcd-backup-restore'
  labels:
    {{- include "kubedb-kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --data-dir=${dataDir:=/var/lib/etcd}
  - --member-name=${memberName:=}
  - --initial-cluster=${initialCluster:=}
  - --initial-cluster-token=${initialClusterToken:=}
  - --peer-urls=${peerURLs:=}
  - --skip-hash-check=${skipHashCheck:=true}
  - --skip-version-check=${skipVersionCheck:=false}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubedb/etcd-restic-plugin") $) }}:v0.1.0{{ include "catalog.ubi" $ }}'
{{ end }}
