apiVersion: catalog.kubedb.com/v1alpha1
kind: ClickHouseVersion
metadata:
  name: 26.2.6
spec:
  clickHouseKeeper:
    image: docker.io/clickhouse/clickhouse-keeper:26.2.6
  db:
    image: dhi.io/clickhouse-server:26.2
  initContainer:
    image: ghcr.io/kubedb/clickhouse-init:24.4.1-v3
  securityContext:
    runAsUser: 101
  updateConstraints:
    allowlist:
    - '>= 26.2.6'
  version: 26.2.6
