apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: neo4j-restore
spec:
  args:
    - restore
    - --namespace=${namespace:=default}
    - --restoresession=${restoreSession:=}
    - --wait-timeout=${waitTimeout:=300}
    - --snapshot=${snapshot:=}
    - --neo4j-admin-args=${neo4jAdminArgs:=}
    - --databases=${databases:=}
    - --seed-server-name=${seedServerName:=}
  image: ghcr.io/kubedb/neo4j-backup-plugin:v0.1.0