apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: neo4j-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --wait-timeout=${waitTimeout:=300}
  - --neo4j-admin-args=${neo4jAdminArgs:=}
  - --exclude-databases=${excludeDatabases:=}
  - --databases=${databases:=}
  - --from=${from:=}
  image: ghcr.io/kubedb/neo4j-backup-plugin:v0.2.0
