---
# Source: kubedb/charts/sidekick/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedb-sidekick
  labels:
    helm.sh/chart: sidekick-v2024.11.8
    app.kubernetes.io/name: sidekick
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/version: "v0.0.10"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedb-sidekick
subjects:
- kind: ServiceAccount
  name: kubedb-sidekick
  namespace: kubedb
