apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: etcd-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --data-dir=${dataDir:=/var/lib/etcd}
  - --member-name=${memberName:=}
  - --initial-cluster=${initialCluster:=}
  - --initial-cluster-token=${initialClusterToken:=}
  - --peer-urls=${peerURLs:=}
  - --skip-hash-check=${skipHashCheck:=true}
  - --skip-version-check=${skipVersionCheck:=false}
  availableVersions:
  - 3.5.21
  - 3.6.4
  image: ghcr.io/kubedb/etcd-restic-plugin:v0.1.0-rc.2_${DB_VERSION}
