apiVersion: catalog.kubedb.com/v1alpha1
kind: MilvusVersion
metadata:
  name: 3.0.0
spec:
  db:
    image: ghcr.io/appscode-images/milvus:3.0.0
  archiver:
    addon:
      name: milvus-addon
      tasks:
        fullBackup:
          name: physical-backup
        fullBackupRestore:
          name: physical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
        volumeSnapshot:
          name: volume-snapshot
    walg:
      image: ghcr.io/kubedb/milvus-archiver:v0.1.0-rc.0
  etcdVersion: v3.5.25
  securityContext:
    runAsUser: 1000
  version: 3.0.0
