apiVersion: catalog.kubedb.com/v1alpha1
kind: MilvusVersion
metadata:
  name: 2.6.1
spec:
  version: "2.6.1"
  db:
    image: urmibiswas/milvus-nonroot:2.6.1
  deprecated: false
  securityContext:
    runAsUser: 1000 