apiVersion: catalog.kubedb.com/v1alpha1
kind: MilvusVersion
metadata:
  name: 3.0.0
spec:
  db:
    image: ghcr.io/appscode-images/milvus:3.0.0
  etcdVersion: v3.5.25
  securityContext:
    runAsUser: 1000
  version: 3.0.0
