apiVersion: catalog.kubedb.com/v1alpha1
kind: OracleVersion
metadata:
  name: 21.3.0
spec:
  coordinator:
    image: ghcr.io/kubedb/oracle-coordinator:v0.9.0
  dataGuard:
    initContainer:
      image: docker.io/library/busybox:1.36
    observer:
      image: container-registry.oracle.com/database/enterprise:21.3.0.0
  db:
    baseOS: debian
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
  exporter:
    image: container-registry.oracle.com/database/observability-exporter:2.2.1
  initContainer:
    image: ghcr.io/kubedb/oracle-init:v0.2.0
  securityContext:
    runAsUser: 54321
  updateConstraints:
    allowlist:
    - 21.3.1
  version: 21.3.0
