apiVersion: catalog.kubedb.com/v1alpha1
kind: ClickHouseVersion
metadata:
  name: 26.2.6
spec:
  archiver:
    addon:
      name: clickhouse-addon
      tasks:
        fullBackup:
          name: logical-backup
        fullBackupRestore:
          name: logical-backup-restore
        incBackupRestore:
          name: incremental-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
    walg:
      image: ghcr.io/kubedb/clickhouse-backup-plugin:v0.3.0
  clickHouseKeeper:
    image: docker.io/clickhouse/clickhouse-keeper:26.2.6
  db:
    image: docker.io/clickhouse/clickhouse-server:26.2.6
  gitSyncer:
    image: registry.k8s.io/git-sync/git-sync:v4.4.2
  initContainer:
    image: ghcr.io/kubedb/clickhouse-init:24.4.1-v3
  securityContext:
    runAsUser: 101
  updateConstraints:
    allowlist:
    - '>= 26.2.6'
  version: 26.2.6
