apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ace-user-roles/templates/appcatalog/appcatalog-user-roles.yaml
- ace-user-roles/templates/kubedb/autoscaler.yaml
- ace-user-roles/templates/kubedb/core.yaml
- ace-user-roles/templates/kubedb/ops-manager.yaml
- ace-user-roles/templates/kubedb/schema-manager.yaml
- ace-user-roles/templates/license-proxyserver/license-checker-cluster-role.yaml
- ace-user-roles/templates/license-proxyserver/license-reader-cluster-role.yaml
- ace-user-roles/templates/metrics/metrics-user-roles.yaml
- kubedb-autoscaler/crds/node.k8s.appscode.com_nodetopologies.yaml
- kubedb-autoscaler/templates/cluster-role-binding.yaml
- kubedb-autoscaler/templates/cluster-role.yaml
- kubedb-autoscaler/templates/deployment.yaml
- kubedb-autoscaler/templates/license-checker-cluster-role-binding.yaml
- kubedb-autoscaler/templates/license-reader-cluster-role-binding.yaml
- kubedb-autoscaler/templates/license.yaml
- kubedb-autoscaler/templates/service.yaml
- kubedb-autoscaler/templates/serviceaccount.yaml
- kubedb-catalog/crds/catalog.kubedb.com_cassandraversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_clickhouseversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_druidversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_elasticsearchversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_etcdversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_ferretdbversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_kafkaconnectorversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_kafkaversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_mariadbversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_memcachedversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_mongodbversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_mssqlserverversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_mysqlversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_perconaxtradbversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_pgbouncerversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_pgpoolversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_postgresversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_proxysqlversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_rabbitmqversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_redisversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_schemaregistryversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_singlestoreversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_solrversions.yaml
- kubedb-catalog/crds/catalog.kubedb.com_zookeeperversions.yaml
- kubedb-catalog/templates/elasticsearch/deprecated-elasticsearch-7.3.2-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/deprecated-elasticsearch-7.6.1-opendistro.yaml
- kubedb-catalog/templates/elasticsearch/deprecated-elasticsearch-7.9.1-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-1.1.0-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-1.2.4-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-1.3.13-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-1.3.18-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-1.3.19-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.0.1-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.11.1-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.14.0-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.16.0-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.17.1-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.18.0-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.5.0-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-2.8.0-opensearch.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-6.8.23-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.13.4-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.14.2-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.16.3-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.17.15-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.17.23-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.17.25-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-7.9.3-searchguard.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.11.1-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.11.4-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.13.4-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.14.1-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.14.3-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.15.0-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.15.4-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.16.0-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.2.3-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.5.3-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.6.2-elasticstack.yaml
- kubedb-catalog/templates/elasticsearch/elasticsearch-8.8.2-elasticstack.yaml
- kubedb-catalog/templates/kafka/kafka-3.5.2.yaml
- kubedb-catalog/templates/kafka/kafka-3.6.1.yaml
- kubedb-catalog/templates/kafka/kafka-3.7.2.yaml
- kubedb-catalog/templates/kafka/kafka-3.8.1.yaml
- kubedb-catalog/templates/kafka/kafka-3.9.0.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-0.13.0-gcs.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-1.13.1-mongodb.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-1.14.1-mongodb.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.15.0-s3.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.6.1-jdbc.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.7.4-jdbc.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.7.4-mysql.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-2.7.4-postgres.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-3.0.5-jdbc.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-3.0.5-mysql.yaml
- kubedb-catalog/templates/kafkaconnector/kafkaconnector-3.0.5-postgres.yaml
- kubedb-catalog/templates/mariadb/mariadb-10.10.7.yaml
- kubedb-catalog/templates/mariadb/mariadb-10.11.6.yaml
- kubedb-catalog/templates/mariadb/mariadb-10.4.32.yaml
- kubedb-catalog/templates/mariadb/mariadb-10.5.23.yaml
- kubedb-catalog/templates/mariadb/mariadb-10.6.16.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.0.4.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.1.3.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.2.2.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.3.2.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.4.3.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.5.2.yaml
- kubedb-catalog/templates/mariadb/mariadb-11.6.2.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-3.4-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-3.4.22-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-3.6-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-3.6.13-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-4.0.11-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-4.0.5-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-4.1.13-official.yaml
- kubedb-catalog/templates/mongodb/deprecated-mongodb-4.1.7-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-4.2.24-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-4.2.24-percona.yaml
- kubedb-catalog/templates/mongodb/mongodb-4.4.26-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-4.4.26-percona.yaml
- kubedb-catalog/templates/mongodb/mongodb-5.0.23-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-5.0.23-percona.yaml
- kubedb-catalog/templates/mongodb/mongodb-5.0.26-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-6.0.12-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-6.0.12-percona.yaml
- kubedb-catalog/templates/mongodb/mongodb-7.0.16-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-7.0.4-percona.yaml
- kubedb-catalog/templates/mongodb/mongodb-7.0.5-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-7.0.8-official.yaml
- kubedb-catalog/templates/mongodb/mongodb-8.0.4-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-5.7.25-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-5.7.29-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-5.7.31-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-8.0.14-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-8.0.20-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-8.0.21-official.yaml
- kubedb-catalog/templates/mysql/deprecated-mysql-8.0.3-official.yaml
- kubedb-catalog/templates/mysql/mysql-5.7.42-official.yaml
- kubedb-catalog/templates/mysql/mysql-5.7.44-official.yaml
- kubedb-catalog/templates/mysql/mysql-8.0.31-mysql.yaml
- kubedb-catalog/templates/mysql/mysql-8.0.35-official.yaml
- kubedb-catalog/templates/mysql/mysql-8.0.36-official.yaml
- kubedb-catalog/templates/mysql/mysql-8.1.0-official.yaml
- kubedb-catalog/templates/mysql/mysql-8.2.0-official.yaml
- kubedb-catalog/templates/mysql/mysql-8.4.2-official.yaml
- kubedb-catalog/templates/mysql/mysql-8.4.3-official.yaml
- kubedb-catalog/templates/mysql/mysql-9.0.1-official.yaml
- kubedb-catalog/templates/mysql/mysql-9.1.0-official.yaml
- kubedb-catalog/templates/postgres/deprecated-postgres-10.2-official.yaml
- kubedb-catalog/templates/postgres/deprecated-postgres-10.6-official.yaml
- kubedb-catalog/templates/postgres/deprecated-postgres-11.1-official.yaml
- kubedb-catalog/templates/postgres/deprecated-postgres-9.6-official.yaml
- kubedb-catalog/templates/postgres/deprecated-postgres-9.6.7-official.yaml
- kubedb-catalog/templates/postgres/postgres-10.23-official.yaml
- kubedb-catalog/templates/postgres/postgres-11.22-official.yaml
- kubedb-catalog/templates/postgres/postgres-11.22-postgis.yaml
- kubedb-catalog/templates/postgres/postgres-12.17-official.yaml
- kubedb-catalog/templates/postgres/postgres-12.18-postgis.yaml
- kubedb-catalog/templates/postgres/postgres-12.22-official.yaml
- kubedb-catalog/templates/postgres/postgres-13.13-official.yaml
- kubedb-catalog/templates/postgres/postgres-13.14-postgis.yaml
- kubedb-catalog/templates/postgres/postgres-13.14-timescaledb.yaml
- kubedb-catalog/templates/postgres/postgres-13.18-official.yaml
- kubedb-catalog/templates/postgres/postgres-14.10-official.yaml
- kubedb-catalog/templates/postgres/postgres-14.11-postgis.yaml
- kubedb-catalog/templates/postgres/postgres-14.11-timescaledb.yaml
- kubedb-catalog/templates/postgres/postgres-14.13-official.yaml
- kubedb-catalog/templates/postgres/postgres-14.15-official.yaml
- kubedb-catalog/templates/postgres/postgres-15.10-official.yaml
- kubedb-catalog/templates/postgres/postgres-15.5-official.yaml
- kubedb-catalog/templates/postgres/postgres-15.6-official.yaml
- kubedb-catalog/templates/postgres/postgres-15.6-postgis.yaml
- kubedb-catalog/templates/postgres/postgres-15.8-official.yaml
- kubedb-catalog/templates/postgres/postgres-16.1-official.yaml
- kubedb-catalog/templates/postgres/postgres-16.2-official.yaml
- kubedb-catalog/templates/postgres/postgres-16.2-postgis.yaml
- kubedb-catalog/templates/postgres/postgres-16.4-official.yaml
- kubedb-catalog/templates/postgres/postgres-16.6-official.yaml
- kubedb-catalog/templates/postgres/postgres-17.2-official.yaml
- kubedb-catalog/templates/rabbitmq/rabbitmq-3.12.12.yaml
- kubedb-catalog/templates/rabbitmq/rabbitmq-3.13.2.yaml
- kubedb-catalog/templates/rabbitmq/rabbitmq-4.0.4.yaml
- kubedb-catalog/templates/redis/deprecated-redis-4.0.6.yaml
- kubedb-catalog/templates/redis/deprecated-redis-4.0.yaml
- kubedb-catalog/templates/redis/redis-4.0.11.yaml
- kubedb-catalog/templates/redis/redis-5.0.14.yaml
- kubedb-catalog/templates/redis/redis-6.0.20.yaml
- kubedb-catalog/templates/redis/redis-6.2.14.yaml
- kubedb-catalog/templates/redis/redis-6.2.16.yaml
- kubedb-catalog/templates/redis/redis-7.0.14.yaml
- kubedb-catalog/templates/redis/redis-7.0.15.yaml
- kubedb-catalog/templates/redis/redis-7.2.3.yaml
- kubedb-catalog/templates/redis/redis-7.2.4.yaml
- kubedb-catalog/templates/redis/redis-7.2.6.yaml
- kubedb-catalog/templates/redis/redis-7.4.0.yaml
- kubedb-catalog/templates/redis/redis-7.4.1.yaml
- kubedb-catalog/templates/schemaregistry/schemaregistry-2.5.11-apicurio.yaml
- kubedb-catalog/templates/schemaregistry/schemaregistry-3.15.0-aiven.yaml
- kubedb-crd-manager/templates/cluster-role-binding.yaml
- kubedb-crd-manager/templates/cluster-role.yaml
- kubedb-crd-manager/templates/job.yaml
- kubedb-crd-manager/templates/serviceaccount.yaml
- kubedb-kubestash-catalog/crds/addons.kubestash.com_addons.yaml
- kubedb-kubestash-catalog/crds/addons.kubestash.com_functions.yaml
- kubedb-kubestash-catalog/templates/elasticsearch/elasticsearch-addon.yaml
- kubedb-kubestash-catalog/templates/elasticsearch/elasticsearch-backup.yaml
- kubedb-kubestash-catalog/templates/elasticsearch/elasticsearch-dashboard-backup.yaml
- kubedb-kubestash-catalog/templates/elasticsearch/elasticsearch-dashboard-restore.yaml
- kubedb-kubestash-catalog/templates/elasticsearch/elasticsearch-restore.yaml
- kubedb-kubestash-catalog/templates/kubedbmanifest/kubedbmanifest-backup.yaml
- kubedb-kubestash-catalog/templates/kubedbmanifest/kubedbmanifest-restore.yaml
- kubedb-kubestash-catalog/templates/kubedbverifier/kubedbverifier.yaml
- kubedb-kubestash-catalog/templates/mariadb/mariadb-addon.yaml
- kubedb-kubestash-catalog/templates/mariadb/mariadb-backup.yaml
- kubedb-kubestash-catalog/templates/mariadb/mariadb-csi-snapshotter.yaml
- kubedb-kubestash-catalog/templates/mariadb/mariadb-restore.yaml
- kubedb-kubestash-catalog/templates/mongodb/mongodb-addon.yaml
- kubedb-kubestash-catalog/templates/mongodb/mongodb-backup.yaml
- kubedb-kubestash-catalog/templates/mongodb/mongodb-csi-snapshotter.yaml
- kubedb-kubestash-catalog/templates/mongodb/mongodb-restore.yaml
- kubedb-kubestash-catalog/templates/mysql/mysql-addon.yaml
- kubedb-kubestash-catalog/templates/mysql/mysql-backup.yaml
- kubedb-kubestash-catalog/templates/mysql/mysql-csi-snapshotter.yaml
- kubedb-kubestash-catalog/templates/mysql/mysql-physical-backup.yaml
- kubedb-kubestash-catalog/templates/mysql/mysql-physical-restore.yaml
- kubedb-kubestash-catalog/templates/mysql/mysql-restore.yaml
- kubedb-kubestash-catalog/templates/opensearch/opensearch-addon.yaml
- kubedb-kubestash-catalog/templates/opensearch/opensearch-backup.yaml
- kubedb-kubestash-catalog/templates/opensearch/opensearch-dashboard-backup.yaml
- kubedb-kubestash-catalog/templates/opensearch/opensearch-dashboard-restore.yaml
- kubedb-kubestash-catalog/templates/opensearch/opensearch-restore.yaml
- kubedb-kubestash-catalog/templates/postgres/postgres-addon.yaml
- kubedb-kubestash-catalog/templates/postgres/postgres-backup.yaml
- kubedb-kubestash-catalog/templates/postgres/postgres-csi-snapshotter.yaml
- kubedb-kubestash-catalog/templates/postgres/postgres-physical-backup-restore.yaml
- kubedb-kubestash-catalog/templates/postgres/postgres-physical-backup.yaml
- kubedb-kubestash-catalog/templates/postgres/postgres-restore.yaml
- kubedb-kubestash-catalog/templates/redis/redis-addon.yaml
- kubedb-kubestash-catalog/templates/redis/redis-backup.yaml
- kubedb-kubestash-catalog/templates/redis/redis-restore.yaml
- kubedb-ops-manager/crds/supervisor.appscode.com_recommendations.yaml
- kubedb-ops-manager/templates/cluster-role-binding.yaml
- kubedb-ops-manager/templates/cluster-role.yaml
- kubedb-ops-manager/templates/deployment.yaml
- kubedb-ops-manager/templates/license-checker-cluster-role-binding.yaml
- kubedb-ops-manager/templates/license-reader-cluster-role-binding.yaml
- kubedb-ops-manager/templates/license.yaml
- kubedb-ops-manager/templates/service.yaml
- kubedb-ops-manager/templates/serviceaccount.yaml
- kubedb-provisioner/templates/cluster-role-binding.yaml
- kubedb-provisioner/templates/cluster-role.yaml
- kubedb-provisioner/templates/deployment.yaml
- kubedb-provisioner/templates/license-checker-cluster-role-binding.yaml
- kubedb-provisioner/templates/license-reader-cluster-role-binding.yaml
- kubedb-provisioner/templates/license.yaml
- kubedb-provisioner/templates/service.yaml
- kubedb-provisioner/templates/serviceaccount.yaml
- kubedb-webhook-server/templates/apiregistration.yaml
- kubedb-webhook-server/templates/autoscaler/mutating-webhook.yaml
- kubedb-webhook-server/templates/autoscaler/validating-webhook.yaml
- kubedb-webhook-server/templates/cluster-role-binding.yaml
- kubedb-webhook-server/templates/cluster-role.yaml
- kubedb-webhook-server/templates/dashboard/mutating-webhook.yaml
- kubedb-webhook-server/templates/dashboard/validating-webhook.yaml
- kubedb-webhook-server/templates/deployment.yaml
- kubedb-webhook-server/templates/ops-manager/mutating-webhook.yaml
- kubedb-webhook-server/templates/ops-manager/validating-webhook.yaml
- kubedb-webhook-server/templates/provisioner/mutating-webhook.yaml
- kubedb-webhook-server/templates/provisioner/validating-webhook.yaml
- kubedb-webhook-server/templates/schema-manager/mutating-webhook.yaml
- kubedb-webhook-server/templates/schema-manager/validating-webhook.yaml
- kubedb-webhook-server/templates/service.yaml
- kubedb-webhook-server/templates/serviceaccount.yaml
- kubedb-webhook-server/templates/webhook-eas-rbac.yaml
- petset/crds/apps.k8s.appscode.com_petsets.yaml
- petset/crds/apps.k8s.appscode.com_placementpolicies.yaml
- petset/templates/operator.yaml
- petset/templates/placementpolicies/default.yaml
- petset/templates/rbac/auth_proxy.yaml
- petset/templates/rbac/cluster_role.yaml
- petset/templates/rbac/cluster_role_binding.yaml
- petset/templates/rbac/serviceaccount.yaml
- petset/templates/rbac/user_roles.yaml
- petset/templates/webhook-server/cert.yaml
- petset/templates/webhook-server/deployment.yaml
- petset/templates/webhook-server/monitoring/service.yaml
- petset/templates/webhook-server/mutating_webhook.yaml
- petset/templates/webhook-server/validating_webhook.yaml
- petset/templates/webhook-server/webhook_service.yaml
- sidekick/crds/apps.k8s.appscode.com_sidekicks.yaml
- sidekick/templates/cluster-role-binding.yaml
- sidekick/templates/cluster-role.yaml
- sidekick/templates/deployment.yaml
- sidekick/templates/service.yaml
- sidekick/templates/serviceaccount.yaml
- sidekick/templates/user-roles.yaml
