apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: oracle-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --wait-timeout=${waitTimeout:=300}
  - --snapshot=${snapshot:=}
  image: sadi74/oracle-backup-plugin:oracle-backup_linux_amd64
