apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: oracle-restore
spec:
  args:
  - performRestore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --wait-timeout=${waitTimeout:=300}
  - --snapshot=${snapshot:=}
  - --until-time=${untilTime:=}
  - --until-scn=${untilSCN:=}
  - --restore-spfile=${restoreSPFile:=false}
  - --recover-to-latest=${recoverToLatest:=false}
  - --allow-autobackup-search=${allowAutobackupSearch:=false}
  image: ghcr.io/kubedb/oracle-backup-plugin:v0.1.0
