apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: oracle-backup
spec:
  args:
    - performBackup
    - --namespace=${namespace:=default}
    - --backupsession=${backupSession:=}
    - --wait-timeout=${waitTimeout:=300}
    - --target-pod=${targetPod:=}
  image: ghcr.io/kubedb/oracle-backup-plugin:v0.1.0
