apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: oracle-differential-backup
spec:
  args:
    - differential-backup
    - --namespace=${namespace:=default}
    - --backupsession=${backupSession:=}
    - --wait-timeout=${waitTimeout:=300}
    - --target-pod=${targetPod:=}
    - --interval=${interval:=3600}
  image: sadi74/oracle-backup-plugin:diff-test2
