apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: oracle-backup
spec:
  args:
  - physical-backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --wait-timeout=${waitTimeout:=300}
  image: sadi74/oracle-backup-plugin:remove-addon-tmp
