apiVersion: v2
name: kubedb-courier
version: v0.6.0
appVersion: v0.6.0
kubeVersion: '>=1.26.0-0'
annotations:
  charts.openshift.io/name: kubedb-courier
description: A Helm chart for Kubernetes
type: application
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb/courier
maintainers:
- name: appscode
  email: support@appscode.com
