project:
  name: Database Courier by AppsCodes
  shortName: Database Courier
  url: https://github.com/kubedb
  description: Community features for KubeDB by AppsCode
  app: a Database Courier operator
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubedb-courier
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.20+
release:
  name: kubedb-courier
  namespace: kubedb
