{{- template "kubedb-catalog.refresh-versions" . }}

{{ $featureGates := .Values.featureGates }}
{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and $featureGates.Etcd (not (eq $ubi "operator")) }}


apiVersion: catalog.kubedb.com/v1alpha1
kind: EtcdVersion
metadata:
  name: '3.5.21'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.ghcr" (merge (dict "_repo" "appscode-images/etcd") $) }}:v3.5.21'
  exporter:
    image: '{{ include "image.ghcr" (merge (dict "_repo" "appscode-images/etcd") $) }}:v3.5.21'
  securityContext:
    runAsUser: 1000
  updateConstraints:
    allowlist:
    - '>= 3.5.21, <= 3.6.4'
  version: 3.5.21
{{ end }}
