resources:
  - ../base

patches:
  - path: kubedb-crd-manager/cluster-role.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: kubedb-kubedb-crd-manager
  - path: kubedb-crd-manager/cluster-role-binding.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: kubedb-kubedb-crd-manager
  - path: kubedb-crd-manager/serviceaccount.yaml
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: kubedb-kubedb-crd-manager
  - path: kubedb-crd-manager/job.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: kubedb-kubedb-crd-manager
      namespace: kubedb