apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: milvus-local-wal-restore
spec:
  args:
  - local-wal-restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --data-dir=/kubestash-data
  image: ghcr.io/kubedb/milvus-backup-plugin:v0.1.0-rc.0
