apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: milvus-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --wait-timeout=${waitTimeout:=300}
  - --restore-suffix=${restoreSuffix:=_restored}
  image: urmibiswas/milvus-backup-plugin:20260805-170149_linux_amd64
