apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: milvus-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --wait-timeout=${waitTimeout:=300}
  - --restore-suffix=${restoreSuffix:=_restored}
  image: ghcr.io/kubedb/milvus-backup-plugin:v0.1.0-rc.0
