apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: milvus-physical-backup-restore
spec:
  args:
  - physical-restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --verify=${verify:=sample}
  - --parallelism=${parallelism:=16}
  image: ghcr.io/kubedb/milvus-backup-plugin:v0.1.0-rc.0
