apiVersion: v2
name: kubedb-kubestash-blueprints
description: KubeStash BluePrints by AppsCode
type: application
version: v2024.11.18
appVersion: v2024.11.18
home: https://kubestash.com
icon: https://cdn.appscode.com/images/products/stash/stash-community-icon.png
sources:
- https://github.com/kuebstash
maintainers:
- name: appscode
  email: support@appscode.com
