project:
  name: KubeStash BluePrints
  shortName: KubeStash BluePrints
  url: https://github.com/stashed
  description: BluePrints for Databases
  app: Stash BluePrints
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubedb-kubestash-blueprints
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: kubedb-kubestash-blueprints
  namespace: stash
