# Default values for kubedb-kubestash-blueprints.

proxies:
  dockerHub: ""
  dockerLibrary: ""
  ghcr: ghcr.io
  quay: quay.io
  kubernetes: registry.k8s.io
  microsoft: mcr.microsoft.com
  appscode: r.appscode.com

featureGates:
  Druid: true
  Elasticsearch: true
  FerretDB: false
  Kafka: false
  MariaDB: true
  Memcached: false
  MSSQLServer: true
  MongoDB: true
  MySQL: true
  PerconaXtraDB: false
  PgBouncer: false
  Pgpool: false
  Postgres: true
  ProxySQL: false
  RabbitMQ: false
  Redis: true
  Singlestore: true
  Solr: false
  ZooKeeper: false

encryptionSecret:
  name: "" # default-encryption-secret
  namespace: "" # stash
retentionPolicy:
  name: "" # keep-1mo
  namespace: "" # stash
schedule: "" # 0 */2 * * *
storageRef:
  name: "" # default
  namespace: "" # stash
