name: daily-general

on:
  schedule:
    - cron: '0 0 1 1 *'
#    - cron: '0 3 * * 1,5' # At 03:00 on monday and friday
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      test:
        description: 'Test repo branch name'
        required: true
        default: 'master'
        type: string
      installer:
        description: 'Installer repo branch name'
        required: true
        default: 'master'
        type: string
      crd-manager:
        description: 'crd-manager repo branch name'
        required: true
        default: 'master'
        type: string
      petset_installer:
        description: 'petset installer repo branch name'
        required: true
        default: 'master'
        type: string
      petset:
        description: 'petset repo branch name'
        required: true
        default: 'master'
      zookeeper-version:
        description: 'zookeeper version name'
        required: true
        default: '3.7.2'
        type: string
      profiles:
        description: 'Test profile'
        required: true
        default: 'provisioner'
        type: string
      ssl:
        description: 'Use SSL'
        required: true
        default: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-daily-general
  cancel-in-progress: true

jobs:
  config:
    name: Configure Inputs
    runs-on: label-detector
    outputs:
      test: ${{ steps.defaulter.outputs.test }}
      installer: ${{ steps.defaulter.outputs.installer }}
      zookeeper_version: ${{ steps.defaulter.outputs.zookeeper_version }}
      crd_manager: ${{ steps.defaulter.outputs.crd_manager }}
      petset: ${{ steps.defaulter.outputs.petset }}
      petset_installer: ${{ steps.defaulter.outputs.petset_installer }}
      profiles: ${{ steps.defaulter.outputs.profiles }}
      ssl: ${{ steps.defaulter.outputs.ssl }}
    steps:
      - name: Defaulter
        id: defaulter
        env:
          V_TEST: ${{ inputs.test }}
          V_INSTALLER: ${{ inputs.installer }}
          V_CRD_MANAGER: ${{ inputs.crd-manager }}
          V_PETSET: ${{ inputs.petset }}
          V_PETSET_INSTALLER: ${{ inputs.petset_installer }}
          V_PROFILES: ${{ inputs.profiles }}
          V_SSL: ${{ inputs.ssl }}
          V_ZOOKEEPER_VERSION: ${{ inputs.zookeeper-version }}
        run: |
          echo "test=${V_TEST:-master}" >> $GITHUB_OUTPUT
          echo "installer=${V_INSTALLER:-master}" >> $GITHUB_OUTPUT
          echo "crd_manager=${V_CRD_MANAGER:-master}" >> $GITHUB_OUTPUT
          echo "petset=${V_PETSET:-master}" >> $GITHUB_OUTPUT
          echo "petset_installer=${V_PETSET_INSTALLER:-master}" >> $GITHUB_OUTPUT
          echo "zookeeper_version=${V_ZOOKEEPER_VERSION:-3.7.2}" >> $GITHUB_OUTPUT
          echo "profiles=[\"${V_PROFILES:-provisioner}\"]" >> $GITHUB_OUTPUT
          echo "ssl=[\"${V_SSL:-false}\"]" >> $GITHUB_OUTPUT

  test:
    name: Test
    runs-on: testrig
    needs: config
    strategy:
      fail-fast: false
      matrix:
        k8s: [v1.35.0]
        db: [hazelcast]
        version: [9.4.1, 8.11.2]
        target: [9.4.1]
        profiles: ${{ fromJSON(needs.config.outputs.profiles) }}
        ssl: ${{ fromJSON(needs.config.outputs.ssl) }}
    steps:
      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
        id: go

      - uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Prepare host
        run: |
          brew install gh kubectl helm kind

      - name: Prepare git
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          set -x
          git config --global user.name "1gtm"
          git config --global user.email "1gtm@appscode.com"
          git config --global \
            url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf \
            "https://github.com"

      - name: Create Kubernetes ${{ matrix.k8s }} cluster
        id: kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.31.0
          config: hack/kubernetes/kind.yaml
          image: kindest/node:${{ matrix.k8s }}

      - name: Prepare cluster for testing
        id: local-path
        run: |
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes
          kubectl wait --for=condition=Ready pods -n kube-system --all --timeout=10m
          kubectl get pods -n kube-system

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - name: Issue License
        env:
          BYTEBUILDERS_LICENSE_TOKEN: ${{ secrets.BYTEBUILDERS_LICENSE_TOKEN }}
        run: |
          export KUBECONFIG="${HOME}/.kube/config"
          CLUSTER_UID=$(kubectl get ns kube-system -o=jsonpath='{.metadata.uid}')
          curl -X POST -o /tmp/license.txt -d "name=1gtm&email=1gtm@appscode.com&product=kubedb-enterprise&cluster=${CLUSTER_UID}&tos=true&token=${BYTEBUILDERS_LICENSE_TOKEN}" https://license-issuer.appscode.com/issue-license


      - name: Check out installer
        run: |
          cd ..
          git clone https://github.com/kubedb/installer.git
          cd installer
          git checkout ${{ needs.config.outputs.installer }}
      - name: Check out crd-manager
        run: |
          cd ..
          git clone https://github.com/kubedb/crd-manager.git
          cd crd-manager
          git checkout ${{ needs.config.outputs.crd_manager }}

      - name: Check out zookeeper
        run: |
          cd ..
          git clone https://github.com/kubedb/zookeeper.git
          cd zookeeper
          git checkout master
          make push-to-kind

      #      - name: Install stash and addons
      #        env:
      #          LICENSE_FILE: /tmp/license.txt
      #        run: |
      #          make stash-install

      - name: Check out petset installer
        run: |
          cd ../../
          mkdir kubeops.dev
          cd kubeops.dev
          git clone https://github.com/kubeops/installer.git
          cd installer
          git checkout ${{ needs.config.outputs.petset_installer }}

      - name: Check out petset
        run: |
          cd ../../
          cd kubeops.dev
          git clone https://github.com/kubeops/petset.git
          cd petset
          git checkout ${{ needs.config.outputs.petset }}
          make push-to-kind

      - name: Install operator
        env:
          LICENSE_FILE: /tmp/license.txt
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_KEY }}
        run: |
          echo "preparing test credentials"
          mkdir -p hack/config
          echo -n "$TEST_CREDENTIALS" > hack/config/.env
          echo >> hack/config/.env
          echo "GOOGLE_SERVICE_ACCOUNT_JSON_KEY=$(echo $GOOGLE_SERVICE_ACCOUNT_JSON_KEY)" >> hack/config/.env
          make deploy-to-kind install-zookeeper install-petset ZOOKEEPER_TAG=$(docker images | grep zookeeper-operator |  awk '{ print $2 }' | tail -n 1) PETSET_TAG=$(docker images | grep petset |  awk '{ print $2 }' | tail -n 1)

      - name: Run e2e tests
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
          GOOGLE_SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_KEY }}
        run: |
          cd ..
          git clone https://github.com/kubedb/tests.git
          cd tests
          git checkout ${{ needs.config.outputs.test }}
          echo "preparing test credentials"
          mkdir -p hack/config
          echo -n "$TEST_CREDENTIALS" > hack/config/.env
          echo >> hack/config/.env
          echo "GOOGLE_SERVICE_ACCOUNT_JSON_KEY=$(echo $GOOGLE_SERVICE_ACCOUNT_JSON_KEY)" >> hack/config/.env
          make e2e-tests GINKGO_ARGS="--flake-attempts=2 --timeout=24h" TEST_ARGS="--db-type=${{ matrix.db }} --db-version=${{ matrix.version }} --test-profiles=${{ matrix.profiles }} --ssl=${{ matrix.ssl }} --restricted=false --dependencies=zookeeper=${{ needs.config.outputs.zookeeper_version }}" \
          || (kubectl describe deployment -n kubedb -l 'app.kubernetes.io/name in (kubedb-provisioner,kubedb-ops-manager)'; \
              kubectl logs -n kubedb -l 'app.kubernetes.io/name in (kubedb-provisioner,kubedb-ops-manager)'; \
              kubectl describe deployment -n kubedb -l 'app.kubernetes.io/name in (app.kubernetes.io/name=stash-enterprise)'; \
              kubectl logs -n kubedb -l 'app.kubernetes.io/name in (app.kubernetes.io/name=stash-enterprise)'; \
              exit 1;)